# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./_config.yml"

overrides:
  configs:
    - jdk-lxr|g1|common|hs
    - jdk-lxr|ix|common|tph|trace2-1|srv-128|srvw|lfb-32
    - jdk-lxr|ix|common|tph|trace2-2|srv-128|srvw|lfb-32
    - jdk-lxr|ix|common|tph|trace2-3|srv-128|srvw|lfb-32
    - jdk-lxr|ix|common|tph|trace2-5|srv-128|srvw|lfb-32
    - jdk-lxr|ix|common|tph|trace2-10|srv-128|srvw|lfb-32
    - jdk-lxr|ix|common|tph|trace2-20|srv-128|srvw|lfb-32
    - jdk-lxr|ix|common|tph|trace2-30|srv-128|srvw|lfb-32
    # - jdk-lxr|shenandoah|common|hs

