
benchmarks:
  # dacapochopin-29a657f:
  #   - lusearch
  #   - h2
  #   - cassandra
  #   - tomcat
  #   - fop
  #   - h2o
  #   - avrora
  #   - batik
  #   - biojava
  #   - eclipse
  #   - graphchi
  #   - jython
  #   - luindex
  #   - pmd
  #   - sunflow
  #   - xalan
  #   - zxing
    # - kafka
    # - jme
    # - tradebeans
    # - tradesoap
  # dacapochopin-f480064:
  dacapochopin-6e411f33:
    - lusearch
    - h2
    - cassandra
    - tomcat
    - tradebeans
    - tradesoap

    # - fop
    # - h2o
    # - avrora
    # - batik
    # - biojava
    # - eclipse
    # - graphchi
    # - jython
    # - luindex
    # - pmd
    # - sunflow
    # - xalan
    # - zxing
    # - kafka

    # - jme
