includes:
  - "../running-ng/config/base/runbms.yml"
  - "./modifiers.yml"

overrides:
  invocations: 20
  suites.dacapochopin-69a704e.timing_iteration: 5
  suites.dacapochopin-69a704e.callback: probe.DacapoChopinCallback
  suites.dacapochopin-69a704e.timeout: 600
  suites.dacapochopin-69a704e.minheap_values.immix-sim:
    avrora: 27
    batik: 968
    biojava: 418
    cassandra: 2325
    eclipse: 2780
    fop: 134
    graphchi: 256
    # h2: .inf
    h2o: 4099
    jme: 236
    jython: 729
    luindex: 55
    lusearch: 1154
    pmd: 1855
    sunflow: 1282
    tomcat: 1482
    # tradebeans: .inf
    # tradesoap: .inf
    xalan: 78
    zxing: 746
  suites.dacapochopin-69a704e.minheap_values.gencopy:
    avrora: 14
    batik: 668
    biojava: 428
    cassandra: 218
    eclipse: 1054
    fop: 44
    graphchi: 256
    # h2: 1154 # ???
    h2o: 1013
    jme: 236
    jython: 112
    # Java version '15.0.2' is incompatable with kafka: Kafka currently requires Java 8 due to 'java.lang.NoClassDefFoundError: javax/activation/DataSource' error for more recent Java releases.
    # kafka: inf
    luindex: 54
    lusearch: 418
    pmd: 3964
    sunflow: 52
    tomcat: 120
    # tradebeans: 169 # ???
    # tradesoap: 133 # ???
    xalan: 36
    zxing: 560
  suites.dacapochopin-69a704e.minheap_values.immix-rc:
    avrora: 13
    batik: 429
    biojava: 270
    cassandra: 281
    eclipse: 825
    fop: 43
    graphchi: 256
    h2: 2216
    h2o: 109
    jme: 236
    jython: 82
    luindex: 34
    lusearch: 454
    pmd: 736
    sunflow: 81
    tomcat: 130
    # tradebeans: .inf
    # tradesoap: .inf
    xalan: 45
    zxing: 484

benchmarks:
  dacapochopin-69a704e:
    - avrora
    - batik
    - biojava
    - cassandra
    - eclipse
    - fop
    - graphchi
    # - h2
    - h2o
    - jme
    - jython
    # - kafka
    - luindex
    - lusearch
    - pmd
    - sunflow
    - tomcat
    # - tradebeans
    # - tradesoap
    - xalan
    - zxing
