includes:
  - "./minheap-values.yml"
  - "./modifiers.yml"
  - "./benchmarks.yml"

overrides:
  invocations: 20
  suites.dacapochopin-29a657f.timing_iteration: 5
  suites.dacapochopin-29a657f.callback: probe.DacapoChopinCallback
  suites.dacapochopin-29a657f.timeout: 600
