includes:
  - "../../running-ng/config/base/runbms.yml"

overrides:
  "suites.dacapochopin-69a704e.minheap":
    avrora: 57
    batik: 980
    biojava: 566
    cassandra: 2344
    eclipse: 2824
    fop: 170
    graphchi: 306
    h2: 1154 # ???
    h2o: 978
    jme: 236
    jython: 908
    # Java version '15.0.2' is incompatable with kafka: Kafka currently requires Java 8 due to 'java.lang.NoClassDefFoundError: javax/activation/DataSource' error for more recent Java releases.
    # kafka: inf
    luindex: 153
    lusearch: 732
    pmd: 1913
    sunflow: 1060
    tomcat: 1508
    tradebeans: 169 # ???
    tradesoap: 133 # ???
    xalan: 186
    zxing: 794