# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./common/common-lxr.yml"

overrides:
  heap_range: 3
  invocations: 10
  suites.dacapochopin.minheap: G1

runtimes:
  jdk-mmtk:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk/jdk-11.0.19
    commits:
      mmtk-core: 4220b56eb8
      mmtk-openjdk: e8cf5aaa08
      openjdk: 7caf8f7d
  jdk-mmtk-opt:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-opt/jdk-11.0.19
    commits:
      mmtk-core: 4220b56eb8
      mmtk-openjdk: e8cf5aaa08
      openjdk: 7caf8f7d
    features: mmtk/flush_opt

configs:
  - jdk-mmtk|ix|common3|ms|tph
  - jdk-mmtk-opt|ix|common3|ms|tph
