# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./common/common-lxr.yml"

overrides:
  heap_range: 3
  invocations: 40
  suites.dacapochopin-04132797.minheap: G1
  benchmarks.dacapochopin-04132797:
    - lusearch
    - cassandra
    - h2
    - tomcat
    - spring
    - tradesoup
    - tradebeans

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr/jdk-11.0.19
    commits:
      mmtk-core: lxr
      mmtk-openjdk: lxr
      openjdk: 7caf8f7d
  jdk-lxr-1:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-1/jdk-11.0.19
    commits:
      mmtk-core: lxr-merge-debug
      mmtk-openjdk: lxr
      openjdk: 7caf8f7d
  jdk-lxr-2:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-2/jdk-11.0.19
    commits:
      mmtk-core: lxr-merge-debug-2
      mmtk-openjdk: lxr-merge-debug-vo
      openjdk: 7caf8f7d
  jdk-lxr-3:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-3/jdk-11.0.19
    commits:
      mmtk-core: lxr-merge-debug-3
      mmtk-openjdk: lxr-merge-debug-vo
      openjdk: 7caf8f7d
  jdk-lxr-3-fix:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-3-fix/jdk-11.0.19
    commits:
      mmtk-core: lxr-merge-debug-3-fix
      mmtk-openjdk: lxr-merge-debug-vo
      openjdk: 7caf8f7d
  jdk-lxr-3-fix-2:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-3-fix-2/jdk-11.0.19
    commits:
      mmtk-core: lxr-merge-debug-fix-2
      mmtk-openjdk: lxr-merge-debug-vo
      openjdk: 7caf8f7d
  jdk-lxr-3-fix-revert:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-3-fix-revert/jdk-11.0.19
    commits:
      mmtk-core: lxr-merge-debug-3-fix-revert
      mmtk-openjdk: lxr-merge-debug-vo
      openjdk: 7caf8f7d

configs:
  - jdk-lxr|lxr|common3|tph
  - jdk-lxr-1|lxr|common3|tph
  - jdk-lxr-2|lxr|common3|tph
  - jdk-lxr-3|lxr|common3|tph
  - jdk-lxr-3-fix|lxr|common3|tph
  - jdk-lxr-3-fix-2|lxr|common3|tph
  - jdk-lxr-3-fix-revert|lxr|common3|tph
