# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./common/common-lxr.yml"

overrides:
  heap_range: 3
  invocations: 40
  suites.dacapochopin-04132797.minheap: G1

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr/jdk-11.0.19
    commits:
      mmtk-core: 72aad37
      mmtk-openjdk: d382526
      openjdk: 7caf8f7d
  jdk-lxr-20230806:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-20230806/jdk-11.0.19
    commits:
      mmtk-core: 8228e5e5
      mmtk-openjdk: e461a614
      openjdk: 7caf8f7d

configs:
  - jdk-lxr|g1|common3|hs
  - jdk-lxr-20230806|lxr|common3|tph
  - jdk-lxr|lxr|common3|tph
