# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./common/common-lxr.yml"

overrides:
  heap_range: 3
  invocations: 40
  suites.dacapochopin.minheap: G1

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr/jdk-11.0.19
    commits:
      mmtk-core: 1665a55
      mmtk-openjdk: 2cf7c70
      openjdk: 7caf8f7d

configs:
  - jdk-lxr|g1|common3|hs
  - jdk-lxr|lxr|common3|tph
  - jdk-lxr|shenandoah|common3|hs
  - jdk-lxr|z|common3|hs
