# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./common/common-lxr.yml"

overrides:
  heap_range: 3
  invocations: 20
  suites.dacapochopin-rc3.minheap: G1
  benchmarks.dacapochopin-rc3:
    - h2
    # - spring
    # - lusearch

runtimes:
  jdk-lxr-no-meta:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-no-meta/jdk-11.0.19
    commits:
      mmtk-core: 317b6993
      mmtk-openjdk: 61f3be58
      openjdk: narrow-oop-debug
    features: mmtk/no_meta_counting
  jdk-lxr-no-meta-noop-32bit:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-no-meta-noop-32bit/jdk-11.0.19
    commits:
      mmtk-core: 317b6993
      mmtk-openjdk: 61f3be58
      openjdk: narrow-oop-debug
    features: mmtk/no_meta_counting,narrow_oop_mode_32bit
  jdk-lxr-no-meta-noop-shift:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-no-meta-noop-shift/jdk-11.0.19
    commits:
      mmtk-core: 317b6993
      mmtk-openjdk: 61f3be58
      openjdk: narrow-oop-debug
    features: mmtk/no_meta_counting,narrow_oop_mode_shift
  jdk-lxr-no-meta-noop-base-and-shift:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-no-meta-noop-base-and-shift/jdk-11.0.19
    commits:
      mmtk-core: 317b6993
      mmtk-openjdk: 61f3be58
      openjdk: narrow-oop-debug
    features: mmtk/no_meta_counting,narrow_oop_mode_base_and_shift

configs:
  # G1
  - jdk-lxr-no-meta|g1|common3|hs_perf
  # - jdk-lxr-defeatured-no-meta|g1|no_compressed_oops|common3|hs
  # SS (lxr)
  # - jdk-lxr-defeatured-no-meta|ss|common3|tph
  # - jdk-lxr-defeatured-no-meta|ss|no_compressed_oops|common3|tph
  # - jdk-lxr-defeatured-no-meta-discontig|ss|no_compressed_oops|common3|tph
  # IX (lxr)
  - jdk-lxr-no-meta-noop-32bit|ix|common3|tph_perf
  - jdk-lxr-no-meta-noop-shift|ix|common3|tph_perf
  - jdk-lxr-no-meta-noop-base-and-shift|ix|common3|tph_perf
  # LXR (lxr)
  # - jdk-lxr-defeatured-no-meta|lxr|common3|tph
  # - jdk-lxr-defeatured-no-meta|lxr|no_compressed_oops|common3|tph
  # - jdk-lxr-defeatured-no-meta-discontig|lxr|no_compressed_oops|common3|tph
  # - jdk-lxr-no-meta|lxr|common3|tph
  # - jdk-lxr-no-meta|lxr|no_compressed_oops|common3|tph