# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./lxr-mu-debug2.yml"

overrides:
  configs:
    # G1
    - jdk-lxr-no-meta|g1|common3|hs_perf_llc
    # - jdk-lxr-defeatured-no-meta|g1|no_compressed_oops|common3|hs
    # SS (lxr)
    # - jdk-lxr-defeatured-no-meta|ss|common3|tph
    # - jdk-lxr-defeatured-no-meta|ss|no_compressed_oops|common3|tph
    # - jdk-lxr-defeatured-no-meta-discontig|ss|no_compressed_oops|common3|tph
    # IX (lxr)
    - jdk-lxr-no-meta|lxr|lxr_stw|common3|tph_perf_llc
    - jdk-lxr-no-meta-no_weak_ref_barrier|lxr|lxr_stw|common3|tph_perf_llc
    - jdk-lxr-no-meta-two_level_barrier|lxr|lxr_stw|common3|tph_perf_llc
    # - jdk-lxr-no-meta-no_barrier_workaround|lxr|lxr_stw|common3|tph_perf
    - jdk-lxr-no-meta-barrier_skip_const_null|lxr|lxr_stw|common3|tph_perf_llc
    - jdk-lxr-no-meta-barrier_skip_null|lxr|lxr_stw|common3|tph_perf_llc
    - jdk-lxr-no-meta-barrier_skip_const_null-two_level_barrier|lxr|lxr_stw|common3|tph_perf_llc
    - jdk-lxr-no-meta-barrier_skip_null-two_level_barrier|lxr|lxr_stw|common3|tph_perf_llc
    # - jdk-lxr-no-meta|ix|common3|tph_perf|threads-1
    # - jdk-lxr-no-meta-ordered|ix|common3|tph_perf
    # - jdk-lxr-no-meta-prefetch|ix|common3|tph_perf
    # - jdk-lxr-no-meta-prefetch1k|ix|common3|tph_perf
    - jdk-lxr-no-meta|ss|common3|tph_perf_llc