# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./common/common-lxr.yml"

overrides:
  heap_range: 3
  invocations: 5

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr/jdk-11.0.19
    commits:
      mmtk-core: 43a0632ce
      mmtk-openjdk: 848974d7f
      openjdk: 7caf8f7d1
  jdk-lxr-sanity:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-sanity/jdk-11.0.19
    commits:
      mmtk-core: 43a0632ce
      mmtk-openjdk: 848974d7f
      openjdk: 7caf8f7d1
    features: sanity

configs:
  - jdk-lxr|lxr|common3|tph
  - jdk-lxr-sanity|lxr|common3|tph
