# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./common/common-lxr.yml"

overrides:
  heap_range: 3
  invocations: 20
  suites.dacapochopin-rc3.minheap: G1
  # benchmarks.dacapochopin-rc3:
  #   - lusearch
  #   - cassandra
  #   - h2
  #   - tomcat
  #   - spring
  #   - tradesoup
  #   - tradebeans

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr/jdk-11.0.19
    commits:
      mmtk-core: 675b8aed8
      mmtk-openjdk: 2124a4792
      openjdk: 7caf8f7d
  jdk-lxr-no-sweep-clean-only:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-no-sweep-clean-only/jdk-11.0.19
    commits:
      mmtk-core: 50b68a527e
      mmtk-openjdk: 07ea963241
      openjdk: 7caf8f7d
  jdk-lxr-no-sweep:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-no-sweep/jdk-11.0.19
    commits:
      mmtk-core: bad7b8cdb
      mmtk-openjdk: 4bbae7ad9
      openjdk: 7caf8f7d
  jdk-lxr-no-sweep-no-meta:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-no-sweep-no-meta/jdk-11.0.19
    commits:
      mmtk-core: bad7b8cdb
      mmtk-openjdk: 4bbae7ad9
      openjdk: 7caf8f7d
    features: mmtk/no_meta_counting

configs:
  - jdk-lxr|g1|common3|hs_perf
  - jdk-lxr|lxr|common3|tph_perf
  - jdk-lxr-no-sweep-clean-only|lxr|common3|tph_perf
  - jdk-lxr-no-sweep|lxr|common3|tph_perf
  - jdk-lxr-no-sweep-no-meta|lxr|common3|tph_perf
