includes:
  - ./common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 40
  suites.dacapochopin-0d047f55.minheap: g1
  benchmarks.dacapochopin-0d047f55:
    - lusearch

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr/jdk-11.0.19
    commits:
      mmtk-core: 3ee6f84
      mmtk-openjdk: 23a727a
      openjdk: 91259ca9
  jdk-lxr-revert:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-revert/jdk-11.0.19
    commits:
      mmtk-core: bcdcbfe
      mmtk-openjdk: 23a727a
      openjdk: 91259ca9

configs:
  - jdk-lxr|lxr|common3|tph
  - jdk-lxr-revert|lxr|common3|tph
  