# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./common/common-lxr.yml"

overrides:
  heap_range: 3
  invocations: 20
  suites.dacapochopin-rc3.minheap: G1
  benchmarks.dacapochopin-rc3:
    - lusearch
    - cassandra
    - h2
    - tomcat
    - spring
    - tradesoup
    - tradebeans

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr/jdk-11.0.19
    commits:
      mmtk-core: acbc53c43
      mmtk-openjdk: 2124a4792
      openjdk: 7caf8f7d
  jdk-lxr-no-sweep:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr/jdk-11.0.19
    commits:
      mmtk-core: 627a68d206
      mmtk-openjdk: a6e80ca37
      openjdk: 7caf8f7d

configs:
  - jdk-lxr|g1|common3|hs_perf
  - jdk-lxr|lxr|common3|tph_perf
  - jdk-lxr-no-sweep|lxr|common3|tph_perf
