# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./common/common-lxr.yml"

overrides:
  heap_range: 3
  invocations: 40
  suites.dacapochopin-0d047f55.minheap: g1

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr/jdk-11.0.19
    commits:
      mmtk-core: 6d99fdb7
      mmtk-openjdk: 39cb2d67
      openjdk: 91259ca

configs:
  - jdk-lxr|g1|common3|hs
  - jdk-lxr|lxr|common3|tph
