includes:
  - ./common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 40
  suites.dacapochopin-b00bfa9.minheap: g1



runtimes:
  jdk-lxr-bat:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-bat/jdk-11.0.19
    commits:
      mmtk-core: 1a9ba6090
      mmtk-openjdk: c681325
      openjdk: 91259ca9d60
    features: mmtk/lxr_line_256b
  jdk-lxr-no-bat:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-no-bat/jdk-11.0.19
    commits:
      mmtk-core: 0febe9915
      mmtk-openjdk: c681325
      openjdk: 91259ca9d60

configs:
  - jdk-lxr-bat|lxr|common3|tph
  - jdk-lxr-no-bat|lxr|common3|tph
  