# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./common/common-lxr.yml"

overrides:
  heap_range: 3
  invocations: 20
  suites.dacapochopin.minheap: G1
  benchmarks.dacapochopin:
    - lusearch
    - cassandra
    - h2
    - tomcat
    - kafka
    - spring
    - tradebeans
    - tradesoup

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr/jdk-11.0.19
    commits:
      mmtk-core: af8c57004f0
      mmtk-openjdk: f1014a69df3
      openjdk: 7caf8f7d
    features: mmtk/opt

configs:
  - jdk-lxr|g1|common3|hs
  - jdk-lxr|lxr|common3|tph
