includes:
  - ./common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 20
  suites.dacapochopin-0d047f55.minheap: g1

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr/jdk-11.0.19
    commits:
      mmtk-core: 45fcf65
      mmtk-openjdk: 86a5cd2
      openjdk: 91259ca
  jdk-lxr-new-chunklist:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-new-chunklist/jdk-11.0.19
    commits:
      mmtk-core: 0c94864
      mmtk-openjdk: 86a5cd2
      openjdk: 91259ca

configs:
  - jdk-lxr|lxr|common3|tph
  - jdk-lxr-new-chunklist|lxr|common3|tph
  