# running runbms ./evaluation/results/log ./evaluation/configs/lxr-lbo.yml 32 5 9 16 22 27 32 > _log
# ./evaluation/manager run --config lxr-lbo --hfac '32-5-9-16-22-27-32'

includes:
  - "./common/common-lxr.yml"

overrides:
  heap_range: 6
  invocations: 20
  suites.dacapochopin.minheap: LXR
  # benchmarks.dacapochopin:
  #   - lusearch
  #   - cassandra
  #   - h2
  #   - tomcat
  # - kafka
  # - spring
  # - tradebeans
  # - tradesoap

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr/jdk-11.0.19
    commits:
      mmtk-core: 2dd7e41d6d0
      mmtk-openjdk: 73d7b9637
      openjdk: 7caf8f7d
    features: mmtk/opt

configs:
  - jdk-lxr|g1|common3|hs_perf
  - jdk-lxr|lxr|common3|tph_perf
  - jdk-lxr|shenandoah|common3|hs_perf
  - jdk-lxr|z|common3|hs_perf
  - jdk-lxr|parallel|common3|hs_perf
  - jdk-lxr|serial|common3|hs_perf
