# running minheap -a 5 ./evaluation/configs/lxr-minheap.yml ./minheap.yml &> ./minheap.log

includes:
  - ./common/minheap.yml

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: /home/wenyuz/MMTk-Dev/evaluation/builds/jdk-mmtk-lxr/jdk-11.0.19
    commits:
      mmtk-core: c62b108159c
      mmtk-openjdk: f1014a69df3
      openjdk: 7caf8f7d

configs:
  - jdk-lxr|lxr|common3|tph
  - jdk-lxr|g1|common3|hs
