# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./common/common-lxr.yml"

overrides:
  heap_range: 3
  invocations: 40
  suites.dacapochopin-0d047f55.minheap: G1

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr/jdk-11.0.19
    commits:
      mmtk-core: 0486439b2c
      mmtk-openjdk: cb69c9df
      openjdk: 91259ca
  jdk-lxr-cm-fix:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr/jdk-11.0.19
    commits:
      mmtk-core: 633cb3c62bf
      mmtk-openjdk: cb69c9df
      openjdk: 91259ca

configs:
  - jdk-lxr|lxr|common3|tph
  - jdk-lxr-cm-fix|lxr|common3|tph
