includes:
  - ./common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 40
  suites.dacapochopin-b00bfa9.minheap: g1

runtimes:
  jdk-lxr-bat:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-bat/jdk-11.0.19
    commits:
      mmtk-core: e8028d1
      mmtk-openjdk: d8fd433
      openjdk: 91259ca
  jdk-lxr-no-bat:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-no-bat/jdk-11.0.19
    commits:
      mmtk-core: e6c896a
      mmtk-openjdk: d8fd433
      openjdk: 91259ca

configs:
  - jdk-lxr-bat|lxr|common3|tph
  - jdk-lxr-no-bat|lxr|common3|tph
  