# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./common/common-lxr.yml"

overrides:
  heap_range: 3
  invocations: 40
  suites.dacapochopin-rc3.minheap: G1

runtimes:
  jdk-lxr-v019:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-v019/jdk-11.0.19
    commits:
      mmtk-core: 317b6993
      mmtk-openjdk: 366f12ab9
      openjdk: 7caf8f7d
  jdk-lxr-v020:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-v020/jdk-11.0.19
    commits:
      mmtk-core: edfca0ef
      mmtk-openjdk: 8fa93ebc
      openjdk: 7caf8f7d

configs:
  - jdk-lxr-v020|g1|common3|hs
  - jdk-lxr-v020|lxr|common3|tph
  - jdk-lxr-v019|lxr|common3|tph
