includes:
  - ./common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 3
  suites.dacapochopin.minheap: G1

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr/jdk-11.0.19
    commits:
      mmtk-core: 1ee52bc4a
      mmtk-openjdk: 2cf7c70a6
      openjdk: bc9669aae
    features: object_size_distribution
configs:
  - jdk-lxr|lxr|common3|tph
