# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./common/common-lxr.yml"

overrides:
  heap_range: 3
  invocations: 20
  suites.dacapochopin.minheap: G1

runtimes:
  jdk-lxr: &lxr
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-lxr/jdk-11.0.19
    commits: &lxr-commits
      mmtk-core: d27594415
      mmtk-openjdk: e0b27083
      openjdk: bc9669aaed
  jdk-lxr-no-weak-processor-opt:
    <<: *lxr
    home: /$BUILDS/jdk-lxr-no-weak-processor-opt/jdk-11.0.19
    commits:
      <<: *lxr-commits
      mmtk-openjdk: 1149f1c0b

configs:
  - jdk-lxr|lxr|common|tph
  - jdk-lxr-no-weak-processor-opt|lxr|common|tph
