# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./common/common-lxr.yml"

overrides:
  heap_range: 3
  invocations: 40
  suites.dacapochopin.minheap: G1

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-lxr/jdk-11.0.19
    commits:
      mmtk-core: 9aae0cc0f
      mmtk-openjdk: 2cf7c70a63
      openjdk: bc9669aaed
  jdk-lxr-mar2023:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-lxr-2/jdk-11.0.19
    commits:
      mmtk-core: f7e4450e2
      mmtk-openjdk: 27a8307ac
      openjdk: 91259ca9d
  jdk-lxr-jul2023:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-lxr-3/jdk-11.0.19
    commits:
      mmtk-core: ad9314e
      mmtk-openjdk: 98eb6f9f
      openjdk: bc9669aaed

configs:
  # G1
  - jdk-lxr|g1|common3|hs
  - jdk-lxr-jul2023|g1|common3|hs
  # LXR
  - jdk-lxr|lxr|common3|tph
  - jdk-lxr-jul2023|lxr|common3|tph
