includes:
  - ./common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 30
  suites.dacapochopin-0d047f55.minheap: g1

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr/jdk-11.0.19
    commits:
      mmtk-core: c3c84a2
      mmtk-openjdk: 8432f53
      openjdk: 91259ca9
  jdk-lxr-unsafe:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-unsafe/jdk-11.0.19
    commits:
      mmtk-core: 37259d1
      mmtk-openjdk: 8432f53
      openjdk: 91259ca9

configs:
  - jdk-lxr|lxr|common3|tph
  - jdk-lxr-unsafe|lxr|common3|tph
  