# running runbms ./evaluation/results/log ./evaluation/configs/lxr-lbo.yml 32 5 9 16 22 27 32 > _log

# 1     2
# 1208, 1430, 1666, 1916, 2180, 2458, 2750, 3055, 3375, 3708, 4055, 4416, 4791, 5180, 5583, 6000

# 32 2 3 4 8 11 14 16

includes:
  - "./common/common-lxr.yml"

overrides:
  heap_range: 6
  invocations: 3
  suites.dacapochopin.minheap: G1
  benchmarks.dacapochopin:
    - lusearch
    - cassandra
    - h2
    - tomcat
    # - kafka
    # - spring
    # - tradebeans
    # - tradesoap

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr/jdk-11.0.19
    commits:
      mmtk-core: c62b108159c
      mmtk-openjdk: f1014a69df3
      openjdk: 7caf8f7d
    features: mmtk/opt

configs:
  - jdk-lxr|g1|common3|hs
  - jdk-lxr|lxr|common3|tph
  - jdk-lxr|shenandoah|common3|hs
  - jdk-lxr|z|common3|hs
  - jdk-lxr|parallel|common3|hs
  - jdk-lxr|serial|common3|hs
