includes:
  - ./common/common-lxr.yml

overrides:
  heap_range: 8
  invocations: 40
  benchmarks.dacapochopin-04132797:
    - lusearch
    - cassandra
    - h2
    - tomcat

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr/jdk-11.0.19
    commits:
      mmtk-core: d665fb8b
      mmtk-openjdk: 2822c9ce
      openjdk: 91259ca

modifiers:
  perf:
    type: EnvVar
    var: "PERF_EVENTS"
    val: "PERF_COUNT_HW_CPU_CYCLES,PERF_COUNT_HW_INSTRUCTIONS"
  hs_perf:
    type: ModifierSet
    val: "jvmti|jvmti_env|perf"
  mmtk_perf:
    type: EnvVar
    var: "MMTK_PHASE_PERF_EVENTS"
    val: "PERF_COUNT_HW_CPU_CYCLES,0,-1;PERF_COUNT_HW_INSTRUCTIONS,0,-1"

configs:
  - jdk-lxr|g1|common3|hs|hs_perf
  - jdk-lxr|lxr|common3|tph|mmtk_perf
  - jdk-lxr|ss|common3|tph|mmtk_perf
  