# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./common/common-lxr.yml"

overrides:
  heap_range: 3
  invocations: 20
  suites.dacapochopin-rc3.minheap: G1
  benchmarks.dacapochopin-rc3:
    - h2
    - spring
    - lusearch

runtimes:
  jdk-lxr-no-meta:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-no-meta/jdk-11.0.19
    commits:
      mmtk-core: 44080b6ee
      mmtk-openjdk: 73e22d395
      openjdk: 7caf8f7d
    features: mmtk/no_meta_counting
  jdk-lxr-no-meta-defeatured:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-no-meta-defeatured/jdk-11.0.19
    commits:
      mmtk-core: 44080b6ee
      mmtk-openjdk: 73e22d395
      openjdk: 7caf8f7d
    features: mmtk/no_meta_counting,mmtk/lxr_no_lazy,mmtk/lxr_no_cm
  jdk-lxr-no-meta-block-state-fix:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-no-meta-block-state-fix/jdk-11.0.19
    commits:
      mmtk-core: f4779cb46
      mmtk-openjdk: 73e22d395
      openjdk: 7caf8f7d
    features: mmtk/no_meta_counting
  jdk-lxr-no-meta-defeatured-block-state-fix:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-no-meta-defeatured-block-state-fix/jdk-11.0.19
    commits:
      mmtk-core: f4779cb46
      mmtk-openjdk: 73e22d395
      openjdk: 7caf8f7d
    features: mmtk/no_meta_counting,mmtk/lxr_no_lazy,mmtk/lxr_no_cm

configs:
  # G1
  - jdk-lxr-no-meta|g1|common3|hs_perf
  # LXR (lxr)
  - jdk-lxr-no-meta|lxr|common3|tph
  - jdk-lxr-no-meta-defeatured|lxr|common3|tph
  - jdk-lxr-no-meta-block-state-fix|lxr|common3|tph
  - jdk-lxr-no-meta-defeatured-block-state-fix|lxr|common3|tph