# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./common/common-lxr.yml"

overrides:
  heap_range: 3
  invocations: 40
  suites.dacapochopin.minheap: G1

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-lxr/jdk-11.0.19
    commits:
      mmtk-core: 1665a55288
      mmtk-openjdk: 73e22d395
      openjdk: 7caf8f7d
  jdk-lxr-2:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-lxr-2/jdk-11.0.19
    commits:
      mmtk-core: 880d1b523a
      mmtk-openjdk: 2cf7c70a63
      openjdk: bc9669aaed
    features: mmtk/lxr_buf_256,mmtk/local_packet_flush_fix

configs:
  # G1
  - jdk-lxr|g1|common3|hs
  # LXR
  - jdk-lxr|lxr|common3|tph
  - jdk-lxr-2|lxr|common3|tph
