# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 32 7 > _log

includes:
  - "./common/common-lxr.yml"

overrides:
  heap_range: 3
  invocations: 40
  suites.dacapochopin.minheap: LXR
  benchmarks.dacapochopin:
    - lusearch
    - cassandra
    - h2
    - tomcat
    - kafka
    - spring
    - tradebeans
    - tradesoap

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr/jdk-11.0.19
    commits:
      mmtk-core: 2dd7e41d6d0
      mmtk-openjdk: 73d7b9637
      openjdk: 7caf8f7d

configs:
  - jdk-lxr|g1|common3|hs|latency
  - jdk-lxr|lxr|common3|tph|latency
  - jdk-lxr|shenandoah|common3|hs|latency
  - jdk-lxr|z|common3|hs|latency

plugins:
  dacapo-latency:
    patterns:
      - scratch/dacapo-latency-*.csv
      - scratch/dacapo-latency-*.hdr
    type: CopyFile
