# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

# LXR-Ablation-Experiment: Block-Alloc

includes:
  - "./common/common-lxr.yml"

overrides:
  heap_range: 3
  invocations: 20
  suites.dacapochopin.minheap: G1

runtimes:
  jdk-lxr: &lxr
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-lxr/jdk-11.0.19
    commits: &lxr-commits
      mmtk-core: 520622746f1
      mmtk-openjdk: b9df8b5d05a
      openjdk: bc9669aaed
  jdk-lxr-no-block-alloc-opt:
    <<: *lxr
    home: /$BUILDS/jdk-lxr-no-block-alloc-opt/jdk-11.0.19
    commits:
      <<: *lxr-commits
      mmtk-core: 9bf4f2132c4
      mmtk-openjdk: 90da07c04

configs:
  - jdk-lxr|lxr|common|tph
  - jdk-lxr-no-block-alloc-opt|lxr|common|tph
