# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

# LXR-Ablation-Experiment: Block-Alloc

includes:
  - "./common/common-lxr.yml"

overrides:
  heap_range: 3
  invocations: 20
  suites.dacapochopin.minheap: G1

runtimes:
  jdk-lxr: &lxr
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-lxr/jdk-11.0.19
    commits: &lxr-commits
      mmtk-core: 8f76a35015a
      mmtk-openjdk: 46f70a5da6
      openjdk: bc9669aaed
  jdk-lxr-no-block-alloc-opt:
    <<: *lxr
    home: /$BUILDS/jdk-lxr-no-block-alloc-opt/jdk-11.0.19
    commits: &lxr-commits-no-block-alloc-opt
      <<: *lxr-commits
      mmtk-core: 2a093d0f506
      mmtk-openjdk: fb84fed66f5
  jdk-lxr-no-block-alloc-opt-no-bug-fix:
    <<: *lxr
    home: /$BUILDS/jdk-lxr-no-block-alloc-opt-no-bug-fix/jdk-11.0.19
    commits:
      <<: *lxr-commits-no-block-alloc-opt
    features: mmtk/mutator_reused_block_state_bug

configs:
  - jdk-lxr|lxr|common|tph
  - jdk-lxr-no-block-alloc-opt|lxr|common|tph
  - jdk-lxr-no-block-alloc-opt-no-bug-fix|lxr|common|tph
