includes:
  - "/usr/local/lib/python3.6/dist-packages/running/config/base/runbms.yml"

overrides:
  suites.dacapochopin-29a657f.minheap_values.g1:
    avrora: 7
    batik: 1076
    biojava: 191
    cassandra: 263
    eclipse: 534
    fop: 73
    graphchi: 255
    h2: 1191
    h2o: 3689
    jme: 235
    jython: 325
    luindex: 41
    lusearch: 53
    pmd: 637
    sunflow: 87
    tomcat: 71
    xalan: 43
    zxing: 153
  suites.dacapochopin-29a657f.minheap_values.immix-sim:
    avrora: 27
    batik: 968
    biojava: 418
    cassandra: 2325
    eclipse: 2780
    fop: 134
    graphchi: 256
    # h2: .inf
    h2o: 4099
    jme: 236
    jython: 729
    luindex: 55
    lusearch: 1154
    pmd: 1855
    sunflow: 1282
    tomcat: 1482
    # tradebeans: .inf
    # tradesoap: .inf
    xalan: 78
    zxing: 746
  suites.dacapochopin-29a657f.minheap_values.immix:
    avrora: 10
    batik: 457
    biojava: 194
    cassandra: 136
    eclipse: 571
    fop: 30
    graphchi: 256
    h2: 2082
    h2o: 100
    jme: 236
    jython: 71
    luindex: 28
    lusearch: 30
    pmd: 289
    sunflow: 76
    tomcat: 71
    # tradebeans: .inf
    # tradesoap: .inf
    xalan: 20
    zxing: 435
  suites.dacapochopin-29a657f.minheap_values.gencopy:
    avrora: 14
    batik: 668
    biojava: 428
    cassandra: 218
    eclipse: 1054
    fop: 44
    graphchi: 256
    # h2: 1154 # ???
    h2o: 1013
    jme: 236
    jython: 112
    # Java version '15.0.2' is incompatable with kafka: Kafka currently requires Java 8 due to 'java.lang.NoClassDefFoundError: javax/activation/DataSource' error for more recent Java releases.
    # kafka: inf
    luindex: 54
    lusearch: 418
    pmd: 3964
    sunflow: 52
    tomcat: 120
    # tradebeans: 169 # ???
    # tradesoap: 133 # ???
    xalan: 36
    zxing: 560
  suites.dacapochopin-29a657f.minheap_values.immix-rc:
    avrora: 13
    batik: 429
    biojava: 270
    cassandra: 281
    eclipse: 825
    fop: 43
    graphchi: 256
    h2: 2216
    h2o: 1013
    jme: 236
    jython: 112
    luindex: 34
    lusearch: 454
    pmd: 736
    sunflow: 81
    tomcat: 130
    # tradebeans: .inf
    # tradesoap: .inf
    xalan: 45
    zxing: 484
  suites.dacapochopin-29a657f.minheap_values.lxr:
    avrora: 13
    batik: 481
    biojava: 203
    cassandra: 344
    eclipse: 939
    fop: 45
    graphchi: 256
    h2: 2892
    h2o: 124
    jme: 236
    jython: 82
    luindex: 4098
    lusearch: 524
    pmd: 736
    sunflow: 88
    tomcat: 786
    # tradebeans: .inf
    # tradesoap: .inf
    xalan: 58
    zxing: 526
