includes:
  - ./common/common-lxr.yml

overrides:
  heap_range: 8
  invocations: 10

runtimes:
  jdk-mmtk-c32m-tlab4k:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-c32m-tlab4k/jdk-11.0.19
    commits:
      mmtk-core: 522b1ab9
      mmtk-openjdk: cf9cb8a61
      openjdk: 91259ca
    features: mmtk/chunk_32m,mmtk/ss_los_16m,mmtk/ss_tlab_4k
  jdk-mmtk-c32m-tlab2m:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-c32m-tlab2m/jdk-11.0.19
    commits:
      mmtk-core: 522b1ab9
      mmtk-openjdk: cf9cb8a61
      openjdk: 91259ca
    features: mmtk/chunk_32m,mmtk/ss_los_16m,mmtk/ss_tlab_2m
  jdk-mmtk-c4m-tlab32k:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-c4m-tlab32k/jdk-11.0.19
    commits:
      mmtk-core: 522b1ab9
      mmtk-openjdk: cf9cb8a61
      openjdk: 91259ca
  jdk-mmtk-c32m-tlab32k:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-c32m-tlab32k/jdk-11.0.19
    commits:
      mmtk-core: 522b1ab9
      mmtk-openjdk: cf9cb8a61
      openjdk: 91259ca
    features: mmtk/chunk_32m

modifiers:
  perf:
    type: EnvVar
    var: "PERF_EVENTS"
    val: "PERF_COUNT_HW_CPU_CYCLES,PERF_COUNT_HW_INSTRUCTIONS,PERF_COUNT_HW_CACHE_L1D:MISS,PERF_COUNT_HW_CACHE_DTLB:MISS"
  hs_perf:
    type: ModifierSet
    val: "jvmti|jvmti_env|perf"
  mmtk_perf:
    type: EnvVar
    var: "MMTK_PHASE_PERF_EVENTS"
    val: "PERF_COUNT_HW_CPU_CYCLES,0,-1;PERF_COUNT_HW_INSTRUCTIONS,0,-1;PERF_COUNT_HW_CACHE_L1D:MISS,0,-1;PERF_COUNT_HW_CACHE_DTLB:MISS,0,-1"

configs:
  - jdk-mmtk-c32m-tlab4k|g1|common3|hs|hs_perf
  - jdk-mmtk-c32m-tlab4k|ss|common3|tph|mmtk_perf
  - jdk-mmtk-c32m-tlab2m|ss|common3|tph|mmtk_perf
  - jdk-mmtk-c4m-tlab32k|ss|common3|tph|mmtk_perf
  - jdk-mmtk-c32m-tlab32k|ss|common3|tph|mmtk_perf
  