includes:
  - ./common/common-lxr.yml

overrides:
  heap_range: 8
  invocations: 10

runtimes:
  jdk-mmtk-c4m-tlab32k-los64k:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-c4m-tlab32k-los64k/jdk-11.0.19
    commits:
      mmtk-core: c3d9e4b2
      mmtk-openjdk: cf9cb8a61
      openjdk: 91259ca
    features: mmtk/ss_tlab_32k
  jdk-mmtk-c4m-tlab64k-los64k:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-c4m-tlab64k-los64k/jdk-11.0.19
    commits:
      mmtk-core: c3d9e4b2
      mmtk-openjdk: cf9cb8a61
      openjdk: 91259ca
    features: mmtk/ss_tlab_64k

modifiers:
  perf:
    type: EnvVar
    var: "PERF_EVENTS"
    val: "PERF_COUNT_HW_CPU_CYCLES,PERF_COUNT_HW_INSTRUCTIONS,PERF_COUNT_HW_CACHE_L1D:MISS,PERF_COUNT_HW_CACHE_DTLB:MISS"
  hs_perf:
    type: ModifierSet
    val: "jvmti|jvmti_env|perf"
  mmtk_perf:
    type: EnvVar
    var: "MMTK_PHASE_PERF_EVENTS"
    val: "PERF_COUNT_HW_CPU_CYCLES,0,-1;PERF_COUNT_HW_INSTRUCTIONS,0,-1;PERF_COUNT_HW_CACHE_L1D:MISS,0,-1;PERF_COUNT_HW_CACHE_DTLB:MISS,0,-1"

configs:
  - jdk-mmtk-c4m-tlab32k-los64k|g1|common3|hs|hs_perf|no_compressed_oops
  - jdk-mmtk-c4m-tlab32k-los64k|ss|common3|tph|mmtk_perf|no_compressed_oops
  - jdk-mmtk-c4m-tlab64k-los64k|ss|common3|tph|mmtk_perf|no_compressed_oops
