version: "3"
services:
  mmtk-dev-jdk:
    image: mmtk-dev-jdk
    build:
      dockerfile: ./scripts/docker/Dockerfile.jdk
    volumes:
      - .:/root/mmtk-dev
      - .docker/root/.cargo/git:/root/.cargo/git
      - .docker/root/.cargo/registry:/root/.cargo/registry
    profiles:
      - jdk
  mmtk-dev-v8:
    image: mmtk-dev-v8
    build:
      dockerfile: ./scripts/docker/Dockerfile.v8
    volumes:
      - .:/root/mmtk-dev
      - .docker/root/.cargo/git:/root/.cargo/git
      - .docker/root/.cargo/registry:/root/.cargo/registry
    profiles:
      - v8
  mmtk-dev-jks:
    image: mmtk-dev-jks
    build:
      dockerfile: ./scripts/docker/Dockerfile.jks
    volumes:
      - .:/root/mmtk-dev
      - .docker/root/.cargo/git:/root/.cargo/git
      - .docker/root/.cargo/registry:/root/.cargo/registry
    profiles:
      - jks
