# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./_config.yml"

overrides:
  benchmarks.dacapochopin-29a657f:
    - lusearch
    - h2
  configs:
    - jdk-lxr|g1|common|hs
    - jdk-lxr|ix|common|tph|oevac-10|id|incs-256000|defrag_thold-50|mo-60|rc_after_satb-4|nb-4096
    - jdk-lxr|ix|common|tph|oevac-10|id|incs-256000|defrag_thold-50|mo-60|rc_after_satb-4|nb-8192
    - jdk-lxr|ix|common|tph|oevac-10|id|incs-256000|defrag_thold-50|mo-60|rc_after_satb-4|nb-16384
    - jdk-lxr|ix|common|tph|oevac-40|id|incs-256000|defrag_thold-50|mo-60|rc_after_satb-4|nb-4096
    - jdk-lxr|ix|common|tph|oevac-40|id|incs-256000|defrag_thold-50|mo-60|rc_after_satb-4|nb-8192
    - jdk-lxr|ix|common|tph|oevac-40|id|incs-256000|defrag_thold-50|mo-60|rc_after_satb-4|nb-16384
