hfac: 3x

includes:
  - $CONFIGS/common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 5
  suites.dacapochopin.minheap: G1-n5

runtimes:
  jdk-lxr: &lxr
    type: OpenJDK
    release: 11
    home: $BUILDS/jdk-lxr/jdk-11.0.19
    commits:
      mmtk-core: 0da4c87310eeeb182d764b501bd7095a93483f67
      mmtk-openjdk: b3a612e50e7b782ca40d66eb59a562bfdecc2327
      openjdk: bc9669aaed
    features: mmtk/no_meta_counting

configs:
  - jdk-lxr|lxr|common3|tph|no_compressed_oops|mu-1

plugins:
  dacapo-heapdump:
    patterns:
      - scratch/_heapdump/heapdump.*.binpb.zst
    type: CopyFile
