hfac: 3x

includes:
  - $CONFIGS/common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 5
  suites.dacapo2006:
    type: DaCapo
    release: "2006"
    path: /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar
    minheap: G1-n5
    minheap_values:
      G1-n5:
        antlr: 5
        lusearch: 8
        pmd: 21
        xalan: 23
    timing_iteration: 3
    timeout: 120
    callback: probe.Dacapo2006Callback
  benchmarks:
    dacapo2006:
      - antlr
      # - bloat
      # - jython
      - lusearch
      - pmd
      - xalan

runtimes:
  jdk-lxr: &lxr
    type: OpenJDK
    release: 11
    home: $BUILDS/jdk-lxr/jdk-11.0.19
    commits:
      mmtk-core: 0da4c87310eeeb182d764b501bd7095a93483f67
      mmtk-openjdk: b3a612e50e7b782ca40d66eb59a562bfdecc2327
      openjdk: bc9669aaed
    features: mmtk/no_meta_counting

configs:
  - jdk-lxr|lxr|common3|tph|no_compressed_oops

plugins:
  dacapo-heapdump:
    patterns:
      - scratch/_heapdump/heapdump.*.binpb.zst
    type: CopyFile
