hfac: 3x

includes:
  - $CONFIGS/common/common-lxr.yml

overrides:
  heap_range: 6
  invocations: 3
  suites.dacapochopin.minheap: G1-n5

runtimes:
  jdk-mmtk: &lxr
    type: OpenJDK
    release: 11
    home: $BUILDS/jdk-mmtk/jdk-11.0.19
    commits:
      mmtk-core: 0779477da0f76ba137a3213ea3ae545147efa5ec
      mmtk-openjdk: 05a6360527a7f98f25fbd2d67ff710d026c6bd20
      openjdk: bc9669aaed
    features: mmtk/no_meta_counting

configs:
  - jdk-mmtk|ix|common3|tph|no_compressed_oops|mu-1

plugins:
  dacapo-heapdump:
    patterns:
      - scratch/_heapdump/heapdump.*.binpb.zst
    type: CopyFile
