
benchmarks:
  dacapochopin:
    - lusearch
    - h2
    - cassandra
    - tomcat
    - spring
    - tradebeans
    - tradesoap

    - avrora
    - batik
    - biojava
    - eclipse
    - fop
    - graphchi
    - h2o
    - jme
    - jython
    - kafka
    - luindex
    - pmd
    - sunflow
    - xalan
    - zxing
