includes:
  - "$RUNNING_NG_PACKAGE_DATA/base/runbms-anu.yml"

overrides:
  suites.dacapochopin-rc3:
    type: DaCapo
    release: evaluation
    path: /usr/share/benchmarks/dacapo/dacapo-23.9-RC3-chopin.jar
    minheap: temurin-11-G1
    minheap_values:
      temurin-11-G1:
        avrora: 5
        batik: 186
        biojava: 96
        cassandra: 87
        eclipse: 423
        fop: 13
        graphchi: 255
        h2: 771
        h2o: 83
        jme: 29
        jython: 27
        kafka: 201
        luindex: 41
        lusearch: 26
        pmd: 43
        # spring: .inf
        sunflow: 27
        tomcat: 19
        tradebeans: 129
        tradesoap: 113
        xalan: 7
        zxing: 98
      temurin-17-G1:
        avrora: 7
        batik: 190
        biojava: 95
        # cassandra: .inf
        eclipse: 411
        fop: 15
        graphchi: 255
        h2: 773
        # h2o: .inf
        jme: 29
        jython: 25
        kafka: 197
        luindex: 42
        lusearch: 25
        pmd: 45
        # spring: .inf
        sunflow: 27
        tomcat: 21
        tradebeans: 131
        tradesoap: 103
        xalan: 7
        zxing: 101
      G1:
        avrora: 5
        batik: 196
        biojava: 97
        cassandra: 117
        eclipse: 348
        fop: 15
        graphchi: 183
        h2: 745
        h2o: 123
        jme: 29
        jython: 29
        kafka: 205
        luindex: 45
        lusearch: 21
        pmd: 196
        spring: 55
        sunflow: 38
        tomcat: 23
        tradebeans: 135
        tradesoap: 109
        xalan: 15
        zxing: 162
    timing_iteration: 3
    timeout: 120
