# Min-heap measurement

includes:
  - "$RUNNING_NG_PACKAGE_DATA/base/minheap.yml"
  - "./modifiers.yml"

overrides:
  suites.dacapochopin-04132797:
    type: DaCapo
    release: evaluation
    path: /usr/share/benchmarks/dacapo/dacapo-evaluation-git-04132797.jar
    timing_iteration: 5
    timeout: 120
  suites.dacapochopin-04132797.timing_iteration: 5
  suites.dacapochopin-04132797.callback: probe.DacapoChopinCallback
  suites.dacapochopin-04132797.timeout: 600
  maxheap: 2048

benchmarks:
  dacapochopin-04132797:
    - avrora
    - batik
    - biojava
    - cassandra
    - eclipse
    - fop
    - graphchi
    - h2
    - h2o
    # - jme
    - jython
    # Java version '15.0.2' is incompatable with kafka: Kafka currently requires Java 8 due to 'java.lang.NoClassDefFoundError: javax/activation/DataSource' error for more recent Java releases.
    # - kafka
    - luindex
    - lusearch
    # - pmd
    - sunflow
    # - tradebeans
    # - tradesoap
    - tomcat
    - xalan
    - zxing
