# Min-heap measurement

includes:
  - "$RUNNING_NG_PACKAGE_DATA/base/minheap.yml"
  - "./common-lxr.yml"

overrides:
  # suites.dacapochopin:
  #   type: DaCapo
  #   release: evaluation
  #   path: /usr/share/benchmarks/dacapo/dacapo-evaluation-git-04132797.jar
  #   timing_iteration: 5
  #   timeout: 120
  suites.dacapochopin.timing_iteration: 5
  suites.dacapochopin.callback: probe.DacapoChopinCallback
  suites.dacapochopin.timeout: 600
  maxheap: 2048

benchmarks:
  dacapochopin:
    - lusearch
    - h2
    - cassandra
    - tomcat
    - spring
    - tradebeans
    - tradesoap

    - avrora
    - batik
    - biojava
    - eclipse
    - fop
    - graphchi
    - h2o
    - jme
    - jython
    - kafka
    - luindex
    - pmd
    - sunflow
    - xalan
    - zxing
