includes:
  - "$RUNNING_NG_PACKAGE_DATA/base/runbms-anu.yml"

overrides:
  suites.dacapochopin:
    type: DaCapo
    release: evaluation
    path: /usr/share/benchmarks/dacapo/dacapo-23.11-chopin.jar
    minheap: G1
    minheap_values:
      G1:
        avrora: 5
        batik: 177
        biojava: 91
        cassandra: 107
        eclipse: 133
        fop: 13
        graphchi: 177
        h2: 677
        h2o: 65
        jme: 29
        jython: 25
        kafka: 190
        luindex: 33
        lusearch: 17
        pmd: 183
        spring: 45
        sunflow: 29
        tomcat: 19
        tradebeans: 105
        tradesoap: 85
        xalan: 13
        zxing: 75
      G1-n5:
        avrora: 5
        batik: 175
        biojava: 95
        cassandra: 128
        eclipse: 135
        fop: 13
        graphchi: 175
        h2: 681
        h2o: 71
        jme: 29
        jython: 25
        kafka: 194
        luindex: 29
        lusearch: 21
        pmd: 189
        spring: 58
        sunflow: 29
        tomcat: 19
        tradebeans: 135
        tradesoap: 91
        xalan: 13
        zxing: 195
      LXR: # Min of LXR and G1's minheap
        avrora: 5
        batik: 177
        biojava: 95
        cassandra: 97
        eclipse: 133
        fop: 13
        graphchi: 167
        h2: 677
        h2o: 65
        jme: 29
        jython: 25
        kafka: 190
        luindex: 25
        lusearch: 13
        pmd: 183
        spring: 45
        sunflow: 27
        tomcat: 19
        tradebeans: 105
        tradesoap: 85
        xalan: 13
        zxing: 75
    timing_iteration: 3
    timeout: 120
  suites.dacapochopin-rc3:
    type: DaCapo
    release: evaluation
    path: /usr/share/benchmarks/dacapo/dacapo-23.9-RC3-chopin.jar
    minheap: temurin-11-G1
    minheap_values:
      temurin-11-G1:
        avrora: 5
        batik: 186
        biojava: 96
        cassandra: 87
        eclipse: 423
        fop: 13
        graphchi: 255
        h2: 771
        h2o: 83
        jme: 29
        jython: 27
        kafka: 201
        luindex: 41
        lusearch: 26
        pmd: 43
        # spring: .inf
        sunflow: 27
        tomcat: 19
        tradebeans: 129
        tradesoap: 113
        xalan: 7
        zxing: 98
      temurin-17-G1:
        avrora: 7
        batik: 190
        biojava: 95
        # cassandra: .inf
        eclipse: 411
        fop: 15
        graphchi: 255
        h2: 773
        # h2o: .inf
        jme: 29
        jython: 25
        kafka: 197
        luindex: 42
        lusearch: 25
        pmd: 45
        # spring: .inf
        sunflow: 27
        tomcat: 21
        tradebeans: 131
        tradesoap: 103
        xalan: 7
        zxing: 101
      G1:
        avrora: 7
        batik: 193
        biojava: 97
        cassandra: 129
        eclipse: 137
        fop: 15
        graphchi: 184
        h2: 1363
        h2o: 255
        jme: 29
        jython: 29
        kafka: 198
        luindex: 41
        lusearch: 25
        pmd: 202
        spring: 64
        sunflow: 31
        tomcat: 23
        tradebeans: 135
        tradesoap: 91
        xalan: 17
        zxing: 147
    timing_iteration: 3
    timeout: 120
