includes:
  - "$RUNNING_NG_PACKAGE_DATA/base/runbms.yml"

overrides:
  suites.dacapochopin-6e411f33:
    type: DaCapo
    release: evaluation
    path: /usr/share/benchmarks/dacapo/dacapo-evaluation-git-6e411f33.jar
    minheap: temurin-11-G1
    minheap_values:
      temurin-11-G1:
        avrora: 5
        batik: 186
        biojava: 96
        cassandra: 87
        eclipse: 423
        fop: 13
        graphchi: 255
        h2: 771
        h2o: 83
        jme: 29
        jython: 27
        kafka: 201
        luindex: 41
        lusearch: 26
        pmd: 43
        # spring: .inf
        sunflow: 27
        tomcat: 19
        tradebeans: 129
        tradesoap: 113
        xalan: 7
        zxing: 98
      temurin-17-G1:
        avrora: 7
        batik: 190
        biojava: 95
        # cassandra: .inf
        eclipse: 411
        fop: 15
        graphchi: 255
        h2: 773
        # h2o: .inf
        jme: 29
        jython: 25
        kafka: 197
        luindex: 42
        lusearch: 25
        pmd: 45
        # spring: .inf
        sunflow: 27
        tomcat: 21
        tradebeans: 131
        tradesoap: 103
        xalan: 7
        zxing: 101
    timing_iteration: 3
    timeout: 120


  suites.dacapochopin-b00bfa9:
    type: DaCapo
    release: evaluation
    path: /home/wenyuz/dacapo/dacapo-evaluation-git-b00bfa9.jar
    minheap: temurin-11-G1
    minheap_values:
      temurin-11-G1:
        avrora: 5
        batik: 186
        biojava: 96
        cassandra: 87
        eclipse: 423
        fop: 13
        graphchi: 255
        h2: 771
        h2o: 83
        jme: 29
        jython: 27
        kafka: 201
        luindex: 41
        lusearch: 26
        pmd: 43
        # spring: .inf
        sunflow: 27
        tomcat: 19
        tradebeans: 129
        tradesoap: 113
        xalan: 7
        zxing: 98
      temurin-17-G1:
        avrora: 7
        batik: 190
        biojava: 95
        # cassandra: .inf
        eclipse: 411
        fop: 15
        graphchi: 255
        h2: 773
        # h2o: .inf
        jme: 29
        jython: 25
        kafka: 197
        luindex: 42
        lusearch: 25
        pmd: 45
        # spring: .inf
        sunflow: 27
        tomcat: 21
        tradebeans: 131
        tradesoap: 103
        xalan: 7
        zxing: 101
    timing_iteration: 3
    timeout: 120

  suites.dacapochopin-0d047f55:
    type: DaCapo
    release: evaluation
    path: /usr/share/benchmarks/dacapo/dacapo-evaluation-git-0d047f55.jar
    minheap: temurin-11-G1
    minheap_values:
      temurin-11-G1:
        avrora: 5
        batik: 186
        biojava: 96
        cassandra: 87
        eclipse: 423
        fop: 13
        graphchi: 255
        h2: 771
        h2o: 83
        jme: 29
        jython: 27
        kafka: 201
        luindex: 41
        lusearch: 26
        pmd: 43
        # spring: .inf
        sunflow: 27
        tomcat: 19
        tradebeans: 129
        tradesoap: 113
        xalan: 7
        zxing: 98
      temurin-17-G1:
        avrora: 7
        batik: 190
        biojava: 95
        # cassandra: .inf
        eclipse: 411
        fop: 15
        graphchi: 255
        h2: 773
        # h2o: .inf
        jme: 29
        jython: 25
        kafka: 197
        luindex: 42
        lusearch: 25
        pmd: 45
        # spring: .inf
        sunflow: 27
        tomcat: 21
        tradebeans: 131
        tradesoap: 103
        xalan: 7
        zxing: 101
    timing_iteration: 3
    timeout: 120

  suites.dacapochopin-04132797:
    type: DaCapo
    release: evaluation
    path: /usr/share/benchmarks/dacapo/dacapo-evaluation-git-04132797.jar
    minheap: temurin-11-G1
    minheap_values:
      temurin-11-G1:
        avrora: 5
        batik: 186
        biojava: 96
        cassandra: 87
        eclipse: 423
        fop: 13
        graphchi: 255
        h2: 771
        h2o: 83
        jme: 29
        jython: 27
        kafka: 201
        luindex: 41
        lusearch: 26
        pmd: 43
        # spring: .inf
        sunflow: 27
        tomcat: 19
        tradebeans: 129
        tradesoap: 113
        xalan: 7
        zxing: 98
      temurin-17-G1:
        avrora: 7
        batik: 190
        biojava: 95
        # cassandra: .inf
        eclipse: 411
        fop: 15
        graphchi: 255
        h2: 773
        # h2o: .inf
        jme: 29
        jython: 25
        kafka: 197
        luindex: 42
        lusearch: 25
        pmd: 45
        # spring: .inf
        sunflow: 27
        tomcat: 21
        tradebeans: 131
        tradesoap: 103
        xalan: 7
        zxing: 101
    timing_iteration: 3
    timeout: 120

  suites.dacapochopin-29a657f.minheap_values.g1:
    avrora: 7
    batik: 1076
    biojava: 191
    cassandra: 263
    eclipse: 534
    fop: 73
    graphchi: 255
    h2: 1191
    h2o: 3689
    jme: 235
    jython: 325
    luindex: 41
    lusearch: 53
    pmd: 637
    sunflow: 87
    tomcat: 71
    xalan: 43
    zxing: 153
  suites.dacapochopin-29a657f.minheap_values.immix-sim:
    avrora: 27
    batik: 968
    biojava: 418
    cassandra: 2325
    eclipse: 2780
    fop: 134
    graphchi: 256
    # h2: .inf
    h2o: 4099
    jme: 236
    jython: 729
    luindex: 55
    lusearch: 1154
    pmd: 1855
    sunflow: 1282
    tomcat: 1482
    # tradebeans: .inf
    # tradesoap: .inf
    xalan: 78
    zxing: 746
  suites.dacapochopin-29a657f.minheap_values.immix:
    avrora: 10
    batik: 457
    biojava: 194
    cassandra: 136
    eclipse: 571
    fop: 30
    graphchi: 256
    h2: 2082
    h2o: 100
    jme: 236
    jython: 71
    luindex: 28
    lusearch: 30
    pmd: 289
    sunflow: 76
    tomcat: 71
    # tradebeans: .inf
    # tradesoap: .inf
    xalan: 20
    zxing: 435
  suites.dacapochopin-29a657f.minheap_values.gencopy:
    avrora: 14
    batik: 668
    biojava: 428
    cassandra: 218
    eclipse: 1054
    fop: 44
    graphchi: 256
    h2: 2892 # ???
    h2o: 1013
    jme: 236
    jython: 112
    # Java version '15.0.2' is incompatable with kafka: Kafka currently requires Java 8 due to 'java.lang.NoClassDefFoundError: javax/activation/DataSource' error for more recent Java releases.
    # kafka: inf
    luindex: 54
    lusearch: 418
    pmd: 3964
    sunflow: 52
    tomcat: 120
    # tradebeans: 169 # ???
    # tradesoap: 133 # ???
    xalan: 36
    zxing: 560
  suites.dacapochopin-29a657f.minheap_values.immix-rc:
    avrora: 13
    batik: 429
    biojava: 270
    cassandra: 281
    eclipse: 825
    fop: 43
    graphchi: 256
    h2: 2216
    h2o: 1013
    jme: 236
    jython: 112
    luindex: 34
    lusearch: 454
    pmd: 736
    sunflow: 81
    tomcat: 130
    # tradebeans: .inf
    # tradesoap: .inf
    xalan: 45
    zxing: 484
  suites.dacapochopin-29a657f.minheap_values.lxr:
    avrora: 13
    batik: 481
    biojava: 203
    cassandra: 344
    eclipse: 939
    fop: 45
    graphchi: 256
    h2: 2892
    h2o: 124
    jme: 236
    jython: 82
    luindex: 4098
    lusearch: 524
    pmd: 736
    sunflow: 88
    tomcat: 786
    # tradebeans: .inf
    # tradesoap: .inf
    xalan: 58
    zxing: 526
  suites.dacapochopin-f480064.minheap_values.immix:
    avrora: 10
    batik: 457
    biojava: 194
    cassandra: 136
    eclipse: 571
    fop: 30
    graphchi: 256
    h2: 2082
    h2o: 100
    jme: 236
    jython: 71
    luindex: 28
    lusearch: 30
    pmd: 289
    sunflow: 76
    tomcat: 71
    # tradebeans: .inf
    # tradesoap: .inf
    xalan: 20
    zxing: 435
  suites.dacapochopin-f480064.minheap_values.g1:
    avrora: 7
    batik: 1076
    biojava: 191
    cassandra: 263
    eclipse: 534
    fop: 73
    graphchi: 255
    h2: 1191
    h2o: 3689
    jme: 235
    jython: 325
    luindex: 41
    lusearch: 53
    pmd: 637
    sunflow: 87
    tomcat: 71
    xalan: 43
    zxing: 153
    kafka: 201
    tradebeans: 129
    tradesoap: 113
  suites.dacapochopin-6e411f33.minheap_values.g1:
    avrora: 7
    batik: 1076
    biojava: 191
    cassandra: 263
    eclipse: 534
    fop: 73
    graphchi: 255
    h2: 1191
    h2o: 3689
    jme: 235
    jython: 325
    luindex: 41
    lusearch: 53
    pmd: 637
    sunflow: 87
    tomcat: 71
    xalan: 43
    zxing: 153
    kafka: 201
    tradebeans: 129
    tradesoap: 113
  suites.dacapochopin-b00bfa9.minheap_values.g1:
    avrora: 7
    batik: 1076
    biojava: 191
    cassandra: 263
    eclipse: 534
    fop: 73
    graphchi: 255
    h2: 1191
    h2o: 3689
    jme: 235
    jython: 325
    luindex: 41
    lusearch: 53
    pmd: 637
    sunflow: 87
    tomcat: 71
    xalan: 43
    zxing: 153
    kafka: 201
    tradebeans: 129
    tradesoap: 113
  suites.dacapochopin-0d047f55.minheap_values.g1:
    avrora: 7
    batik: 1076
    biojava: 191
    cassandra: 263
    eclipse: 534
    fop: 73
    graphchi: 255
    h2: 1191
    h2o: 3689
    jme: 235
    jython: 325
    luindex: 41
    lusearch: 53
    pmd: 637
    sunflow: 87
    tomcat: 71
    xalan: 43
    zxing: 153
    kafka: 201
    tradebeans: 129
    tradesoap: 113
