# Min-heap measurement

includes:
  - "$RUNNING_NG_PACKAGE_DATA/minheap.yml"
  - "./modifiers.yml"

overrides:
  suites.dacapochopin-04132797.timing_iteration: 5
  suites.dacapochopin-04132797.callback: probe.DacapoChopinCallback
  suites.dacapochopin-04132797.timeout: 600
  maxheap: 4096

benchmarks:
  dacapochopin-69a704e:
    - avrora
    - batik
    - biojava
    - cassandra
    - eclipse
    - fop
    - graphchi
    - h2
    - h2o
    - jme
    - jython
    # Java version '15.0.2' is incompatable with kafka: Kafka currently requires Java 8 due to 'java.lang.NoClassDefFoundError: javax/activation/DataSource' error for more recent Java releases.
    # - kafka
    - luindex
    - lusearch
    - pmd
    - sunflow
    - tradebeans
    - tradesoap
    - tomcat
    - xalan
    - zxing
  dacapochopin-29a657f:
    - avrora
    - batik
    - biojava
    - cassandra
    - eclipse
    - fop
    - graphchi
    - h2
    - h2o
    - jme
    - jython
    # Java version '15.0.2' is incompatable with kafka: Kafka currently requires Java 8 due to 'java.lang.NoClassDefFoundError: javax/activation/DataSource' error for more recent Java releases.
    # - kafka
    - luindex
    - lusearch
    - pmd
    - sunflow
    - tradebeans
    - tradesoap
    - tomcat
    - xalan
    - zxing
  dacapochopin-04132797:
    - avrora
    - batik
    - biojava
    - cassandra
    - eclipse
    - fop
    - graphchi
    - h2
    - h2o
    - jme
    - jython
    # Java version '15.0.2' is incompatable with kafka: Kafka currently requires Java 8 due to 'java.lang.NoClassDefFoundError: javax/activation/DataSource' error for more recent Java releases.
    # - kafka
    - luindex
    - lusearch
    - pmd
    - sunflow
    - tradebeans
    - tradesoap
    - tomcat
    - xalan
    - zxing
