# Min-heap measurement

includes:
  - "$RUNNING_NG_PACKAGE_DATA/base/minheap.yml"
  - "./common-lxr.yml"

overrides:
  suites.dacapochopin.timing_iteration: 5
  suites.dacapochopin.callback: null
  suites.dacapochopin.timeout: 600
  maxheap: 4096

benchmarks:
  dacapochopin:
    - lusearch
    - h2
    - cassandra
    - tomcat
    - spring
    - kafka
    - tradebeans
    - tradesoap

    - avrora
    - batik
    - biojava
    - eclipse
    - fop
    - graphchi
    - h2o
    - jme
    - jython
    - luindex
    - pmd
    - sunflow
    - xalan
    - zxing
