modifiers:
  hotspot_gc:
    type: JVMArg
    val: -XX:+UnlockExperimentalVMOptions -XX:+Use{0}GC
  c2:
    type: JVMArg
    val: "-XX:-TieredCompilation"
    excludes:
      # These two benchmarks exit with code 1
      dacapochopin-69a704e:
        - tradebeans
        - tradesoap
      dacapochopin-29a657f:
        - tradebeans
        - tradesoap
      dacapochopin-f480064:
        - tradebeans
        - tradesoap
      dacapochopin-6e411f33:
        - tradebeans
        - tradesoap
      dacapochopin-b00bfa9:
        - tradebeans
        - tradesoap
      dacapochopin-0d047f55:
        - tradebeans
        - tradesoap
      dacapochopin-04132797:
        - tradebeans
        - tradesoap
      dacapochopin-rc3:
        - tradebeans
        - tradesoap
      dacapochopin:
        - tradebeans
        - tradesoap
  probes_cp:
    type: JVMClasspath
    val: "/home/wenyuz/MMTk-Dev/evaluation/probes /home/wenyuz/MMTk-Dev/evaluation/probes/probes.jar"
  probes:
    type: JVMArg
    val: "-Djava.library.path=/home/wenyuz/MMTk-Dev/evaluation/probes -Dprobes=RustMMTk"
  jvmti0:
    type: JVMArg
    val: "-agentpath:/home/wenyuz/MMTk-Dev/evaluation/probes/libperf_statistics_pfm0.so"
  jvmti_env0:
    type: EnvVar
    var: "LD_PRELOAD"
    val: "/home/wenyuz/MMTk-Dev/evaluation/probes/libperf_statistics_pfm0.so"
  jvmti3:
    type: JVMArg
    val: "-agentpath:/home/wenyuz/MMTk-Dev/evaluation/probes/libperf_statistics_pfm3.so"
  jvmti_env3:
    type: EnvVar
    var: "LD_PRELOAD"
    val: "/home/wenyuz/MMTk-Dev/evaluation/probes/libperf_statistics_pfm3.so"
  perf:
    type: EnvVar
    var: "PERF_EVENTS"
    # AMD
    val: "PERF_COUNT_HW_CPU_CYCLES,PERF_COUNT_HW_INSTRUCTIONS,PERF_COUNT_HW_CACHE_L1D:MISS,PERF_COUNT_HW_CACHE_DTLB:MISS"
    # Intel
    # val: "PERF_COUNT_HW_CACHE_LL:MISS,PERF_COUNT_HW_CPU_CYCLES,PERF_COUNT_HW_INSTRUCTIONS,PERF_COUNT_HW_CACHE_L1D:MISS,PERF_COUNT_HW_CACHE_DTLB:MISS"
  perf_llc:
    type: EnvVar
    var: "PERF_EVENTS"
    # AMD
    val: "PERF_COUNT_HW_CACHE_LL:MISS,PERF_COUNT_HW_CPU_CYCLES,PERF_COUNT_HW_INSTRUCTIONS,PERF_COUNT_HW_CACHE_L1D:MISS,PERF_COUNT_HW_CACHE_DTLB:MISS"
  pretouch:
    type: JVMArg
    val: "-XX:+AlwaysPreTouch"
  add_exports:
    type: JVMArg
    val: "--add-exports java.base/jdk.internal.ref=ALL-UNNAMED"
  hs0:
    type: ModifierSet
    val: "jvmti0|jvmti_env0"
  hs:
    type: ModifierSet
    val: "jvmti3|jvmti_env3"
  hs_perf0:
    type: ModifierSet
    val: "hs0|perf"
  hs_perf:
    type: ModifierSet
    val: "hs|perf"
  hs_perf0_llc:
    type: ModifierSet
    val: "hs0|perf_llc"
  hs_perf_llc:
    type: ModifierSet
    val: "hs|perf_llc"
  mmtk_perf:
    type: EnvVar
    var: "MMTK_PHASE_PERF_EVENTS"
    # AMD
    val: PERF_COUNT_SW_TASK_CLOCK,0,-1;PERF_COUNT_HW_CPU_CYCLES,0,-1;PERF_COUNT_HW_INSTRUCTIONS,0,-1;PERF_COUNT_HW_CACHE_L1D:MISS,0,-1;PERF_COUNT_HW_CACHE_L1I:MISS,0,-1;PERF_COUNT_HW_BRANCH_MISSES,0,-1
    # Intel
    # val: "PERF_COUNT_HW_CACHE_LL:MISS,0,-1;PERF_COUNT_HW_CPU_CYCLES,0,-1;PERF_COUNT_HW_INSTRUCTIONS,0,-1;PERF_COUNT_HW_CACHE_L1D:MISS,0,-1;PERF_COUNT_HW_CACHE_DTLB:MISS,0,-1"
  mmtk_perf_llc:
    type: EnvVar
    var: "MMTK_PHASE_PERF_EVENTS"
    val: "PERF_COUNT_HW_CACHE_LL:MISS,0,-1;PERF_COUNT_SW_TASK_CLOCK,0,-1;PERF_COUNT_HW_CPU_CYCLES,0,-1;PERF_COUNT_HW_INSTRUCTIONS,0,-1;PERF_COUNT_HW_CACHE_L1D:MISS,0,-1;PERF_COUNT_HW_CACHE_DTLB:MISS,0,-1"
  tph_perf:
    type: ModifierSet
    val: "tph|mmtk_perf"
  tph_perf_llc:
    type: ModifierSet
    val: "tph|mmtk_perf_llc"
  hugetlb:
    type: JVMArg
    val: "-XX:+UseTransparentHugePages"
  barrier:
    type: EnvVar
    var: "BARRIER"
    val: "{0}"
  threads:
    type: EnvVar
    var: "MMTK_THREADS"
    val: "{0}"
  ms:
    type: JVMArg
    val: "-XX:MetaspaceSize=1G -XX:+DisableExplicitGC -XX:-UseBiasedLocking"
  ms2:
    type: JVMArg
    val: "-XX:+DisableExplicitGC -XX:-UseBiasedLocking"
  nobl:
    type: JVMArg
    val: "-XX:-UseBiasedLocking"
  mn:
    type: JVMArg
    val: "-Xmn{0} -XX:SurvivorRatio=32 -XX:-UseAdaptiveSizePolicy"
  exit_on_oom:
    type: JVMArg
    val: "-XX:+ExitOnOutOfMemoryError"
  common:
    type: ModifierSet
    val: "ms|s|c2|probes|probes_cp|exit_on_oom|add_exports"
  common2:
    type: ModifierSet
    val: "nobl|s|c2|probes|probes_cp|exit_on_oom|add_exports"
  common3:
    type: ModifierSet
    val: "s|probes|probes_cp|exit_on_oom|add_exports"
  nogc:
    type: EnvVar
    var: "MMTK_PLAN"
    val: "NoGC"
  ix:
    type: EnvVar
    var: "MMTK_PLAN"
    val: "Immix"
  genix:
    type: EnvVar
    var: "MMTK_PLAN"
    val: "GenImmix"
  gencp:
    type: EnvVar
    var: "MMTK_PLAN"
    val: "GenCopy"
  ss:
    type: EnvVar
    var: "MMTK_PLAN"
    val: "SemiSpace"
  epsilon:
    type: ModifierSet
    val: "hotspot_gc-Epsilon"
  g1:
    type: ModifierSet
    val: "hotspot_gc-G1"
  z:
    type: ModifierSet
    val: "hotspot_gc-Z"
  shenandoah:
    type: ModifierSet
    val: "hotspot_gc-Shenandoah"
  parallel:
    type: ModifierSet
    val: "hotspot_gc-Parallel"
  serial:
    type: ModifierSet
    val: "hotspot_gc-Serial"
  g1r:
    type: JVMArg
    val: "-XX:G1HeapRegionSize={0}"
  tlab:
    type: JVMArg
    val: "-XX:TLABSize={0} -XX:-ResizeTLAB"
  lxr:
    type: EnvVar
    var: MMTK_PLAN
    val: LXR
  lxr_pldi:
    type: EnvVar
    var: "MMTK_PLAN"
    val: "Immix"
  mmtk_no_weak:
    type: EnvVar
    var: MMTK_NO_REFERENCE_TYPES
    val: "true"
  mmtk_no_finalizer:
    type: EnvVar
    var: MMTK_NO_FINALIZER
    val: "true"
  gencopy:
    type: EnvVar
    var: "MMTK_PLAN"
    val: "GenCopy"
  no_inline_clone:
    type: JVMArg
    val: -XX:+UnlockDiagnosticVMOptions -XX:-InlineObjectCopy
  no_weak:
    type: JVMArg
    val: -XX:-RegisterReferences
  no_class_unload:
    type: JVMArg
    val: -XX:-ClassUnloading -XX:-ClassUnloadingWithConcurrentMark
  no_compressed_oops:
    type: JVMArg
    val: -XX:-UseCompressedOops -XX:-UseCompressedClassPointers
  defeature:
    type: ModifierSet
    val: no_weak|no_class_unload|no_compressed_oops|mmtk_no_weak|mmtk_no_finalizer
  defeature_with_comp:
    type: ModifierSet
    val: no_weak|no_class_unload|mmtk_no_weak|mmtk_no_finalizer
  defeature_with_finalizer:
    type: ModifierSet
    val: no_weak|no_class_unload|no_compressed_oops|mmtk_no_weak
  defeature2:
    type: ModifierSet
    val: no_class_unload|no_compressed_oops
  defeature3:
    type: ModifierSet
    val: no_compressed_oops
  no_prefetch:
    type: JVMArg
    val: -XX:AllocatePrefetchStyle=0
  xcomp:
    type: JVMArg
    val: -Xcomp
  taskset:
    type: Wrapper
    val: taskset --cpu-list {0}-{1}
  full_threshold:
    type: EnvVar
    var: RC_STOP_PERCENT
    val: "{0}"
