# running runbms ./evaluation/results/log ./evaluation/configs/lxr-modest-heap-conc/config.yml 8 4 8 --skip-oom 1 --skip-timeout 1 > ~/_log

includes:
  - "../common.yml"
  # - "../minheap.yml"

overrides:
  invocations: 20
  suites.dacapochopin-29a657f.minheap: adoptopenjdk-15-G1
  benchmarks.dacapochopin-29a657f:
    - fop
    - lusearch
    - tradebeans
    - tradesoap
    # - h2o
    - avrora
    - batik
    - biojava
    - cassandra
    - eclipse
    - graphchi
    - h2
    # - jme
    - jython
    - kafka
    - luindex
    - pmd
    - sunflow
    - tomcat
    - xalan
    - zxing

runtimes:
  jdk:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/lxr-modest-heap-conc/jdk-{git}/jdk"
  jdk-17:
    type: OpenJDK
    release: 17
    home: "/usr/lib/jvm/temurin-17-amd64"

modifiers:
  nobarrier:
    type: EnvVar
    var: "BARRIER"
    val: "NoBarrier"
  nb:
    type: EnvVar
    var: "NURSERY_BLOCKS"
    val: "{0}"
  nr:
    type: EnvVar
    var: "NURSERY_RATIO"
    val: "{0}"
  noreuse:
    type: EnvVar
    var: "DISABLE_MUTATOR_LINE_REUSING"
    val: "1"
  mu:
    type: ProgramArg
    val: "-t {0}"
  waitlazy:
    type: EnvVar
    var: "NO_GC_UNTIL_LAZY_SWEEPING_FINISHED"
    val: "1"
  nowaitlazy:
    type: EnvVar
    var: "NO_GC_UNTIL_LAZY_SWEEPING_FINISHED"
    val: "0"



configs:
  - jdk|ix|common|tph|mmtk_perf|nr-3|waitlazy # 1/4 Nursery
  - jdk|ix|common|tph|mmtk_perf|nr-1|waitlazy # 1/2 Nursery
  - jdk|ix|common|tph|mmtk_perf|nr-3|nowaitlazy # 1/4 Nursery
  - jdk|ix|common|tph|mmtk_perf|nr-1|nowaitlazy # 1/2 Nursery
  # - jdk|g1|common|hs_perf
  # - jdk|shenandoah|common|hs_perf
  # - jdk|z|common|hs_perf
  # - jdk|shenandoah|common|hs_perf|mu-3
  # - jdk|shenandoah|common|hs_perf|mu-6
  # - jdk|shenandoah|common|hs_perf|mu-12
  # - jdk-17|g1|common|hs_perf
  # - jdk-17|shenandoah|common|hs_perf
  # - jdk-17|z|common|hs_perf