# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "../common.yml"

overrides:
  heap_range: 6
  invocations: 20
  suites.dacapochopin-29a657f.minheap: immix

runtimes:
  jdk-mmtk-master:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/builds/jdk-mmtk-master-a60b7e22e/jdk-11.0.15"
  jdk-mmtk-blockpr:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/builds/jdk-mmtk-blockpr-50ec6767f/jdk-11.0.15"

configs:
  - jdk-mmtk-master|ix|common|tph_perf
  - jdk-mmtk-blockpr|ix|common|tph_perf
