includes:
  - "/home/wenyuz/MMTk-Dev/running-ng/config/base/runbms.yml"

benchmarks:
  dacapochopin-69a704e:
    - avrora
    - batik
    - biojava
    - cassandra
    - eclipse
    - fop
    - graphchi
    - h2
    - h2o
    - jme
    - jython
    - luindex
    - lusearch
    - pmd
    - sunflow
    - tradebeans
    - tradesoap
    - tomcat
    - xalan
    - zxing

overrides:
  "suites.dacapochopin-69a704e.timing_iteration": 5
  "suites.dacapochopin-69a704e.callback": "probe.DacapoChopinCallback"
  "suites.dacapochopin-69a704e.timeout": 600

runtimes:
  nobarrier:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/oo/jdk-no-barrier/jdk"
  objbarrier_side:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/oo/jdk-obj-barrier-side/jdk"
  objbarrier_header:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/oo/jdk-obj-barrier-header/jdk"

modifiers:
  probes_cp:
    type: JVMClasspath
    val: "/home/wenyuz/MMTk-Dev/evaluation/probes /home/wenyuz/MMTk-Dev/evaluation/probes/probes.jar"
  probes:
    type: JVMArg
    val: "-Djava.library.path=/home/wenyuz/MMTk-Dev/evaluation/probes -Dprobes=RustMMTk"

configs:
  - "nobarrier|ms|s|c2|mmtk_gc-GenCopy|tph|probes_cp|probes"
  - "objbarrier_side|ms|s|c2|mmtk_gc-GenCopy|tph|probes_cp|probes"
  - "objbarrier_header|ms|s|c2|mmtk_gc-GenCopy|tph|probes_cp|probes"