# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "../common.yml"
  - "../lxr-modifiers.yml"

overrides:
  invocations: 10
  suites.dacapochopin-29a657f.minheap: huge
  benchmarks.dacapochopin-29a657f:
    - lusearch
    - cassandra
    - tomcat
    - h2
    - fop
    - h2o
    - avrora
    - batik
    - biojava
    - eclipse
    - graphchi
    - jython
    - luindex
    - pmd
    - sunflow
    - xalan
    - zxing

runtimes:
  jdk-lxr-rc:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-rc-{git}/jdk"
  jdk-lxr-rc-evac:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-rc-evac-{git}/jdk"
  jdk-lxr-rc-evac-4m:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-rc-evac-4m-{git}/jdk"

configs:
  - jdk-lxr-rc|g1|common|hs
  - jdk-lxr-rc|ix|common|tph|lfb-32|nb-4096|incs-128000  # 128M + 128K

  - jdk-lxr-rc-evac-4m|ix|common|tph|lfb-32|nb-4096|incs-128000|nodefrag|n-4

  - jdk-lxr-rc-evac-4m|ix|common|tph|lfb-32|nb-4096|incs-128000|sid2|n-4|sid2_threshold-10  # 128M + 128K + evac (n=4, 10%)
  - jdk-lxr-rc-evac-4m|ix|common|tph|lfb-32|nb-4096|incs-128000|sid2|n-8|sid2_threshold-10  # 128M + 128K + evac (n=8, 10%)
  - jdk-lxr-rc-evac-4m|ix|common|tph|lfb-32|nb-4096|incs-128000|sid2|n-16|sid2_threshold-10  # 128M + 128K + evac (n=16, 10%)

  - jdk-lxr-rc-evac-4m|ix|common|tph|lfb-32|nb-4096|incs-128000|sid2|n-4|sid2_threshold-20  # 128M + 128K + evac (n=4, 20%)
  - jdk-lxr-rc-evac-4m|ix|common|tph|lfb-32|nb-4096|incs-128000|sid2|n-8|sid2_threshold-20  # 128M + 128K + evac (n=8, 20%)
  - jdk-lxr-rc-evac-4m|ix|common|tph|lfb-32|nb-4096|incs-128000|sid2|n-16|sid2_threshold-20  # 128M + 128K + evac (n=16, 20%)

  - jdk-lxr-rc-evac-4m|ix|common|tph|lfb-32|nb-4096|incs-128000|sid2|n-4|sid2_threshold-50  # 128M + 128K + evac (n=4, 20%)
  - jdk-lxr-rc-evac-4m|ix|common|tph|lfb-32|nb-4096|incs-128000|sid2|n-8|sid2_threshold-50  # 128M + 128K + evac (n=8, 20%)
  - jdk-lxr-rc-evac-4m|ix|common|tph|lfb-32|nb-4096|incs-128000|sid2|n-16|sid2_threshold-50  # 128M + 128K + evac (n=16, 20%)