# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "../common.yml"
  - "../lxr-modifiers.yml"

overrides:
  invocations: 10
  suites.dacapochopin-29a657f.minheap: huge
  benchmarks.dacapochopin-29a657f:
    - cassandra
    # - lusearch
    # - tomcat
    - h2
    # - fop
    # - h2o
    # - avrora
    # - batik
    # - biojava
    # - eclipse
    # - graphchi
    # - jython
    # - luindex
    # - pmd
    # - sunflow
    # - xalan
    # - zxing

runtimes:
  jdk-lxr-rc:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-rc-{git}/jdk"
  jdk-lxr-rc-evac:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-rc-evac-{git}/jdk"
  jdk-lxr-rc-evac-4m:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-rc-evac-4m-{git}/jdk"

configs:
  - jdk-lxr-rc|g1|common|hs
  - jdk-lxr-rc|ix|common|tph|lfb-32|nb-8192|incs-128000  # 256M + 128K
  - jdk-lxr-rc-evac-4m|ix|common|tph|lfb-32|nb-8192|incs-128000|sid-4  # 256M + 128K + evac (n=4, 4mb)
  - jdk-lxr-rc-evac-4m|ix|common|tph|lfb-32|nb-8192|incs-128000|sid-8  # 256M + 128K + evac (n=8, 4mb)
  - jdk-lxr-rc-evac-4m|ix|common|tph|lfb-32|nb-8192|incs-128000|sid-16  # 256M + 128K + evac (n=16, 4mb)
  # - jdk-lxr-rc-evac-4m|ix|common|tph|lfb-32|nb-8192|incs-128000|sid-4|sidm-8  # 256M + 128K + evac (n=4, 32mb)
  # - jdk-lxr-rc-evac-4m|ix|common|tph|lfb-32|nb-8192|incs-128000|sid-8|sidm-8  # 256M + 128K + evac (n=8, 32mb)
  # - jdk-lxr-rc-evac-4m|ix|common|tph|lfb-32|nb-8192|incs-128000|sid-16|sidm-8  # 256M + 128K + evac (n=16, 32mb)

  - jdk-lxr-rc-evac-4m|ix|common|tph|lfb-32|nb-8192|incs-256000|sid-4  # 256M + 128K + evac (n=4, 4mb)
  - jdk-lxr-rc-evac-4m|ix|common|tph|lfb-32|nb-8192|incs-256000|sid-8  # 256M + 128K + evac (n=8, 4mb)
  - jdk-lxr-rc-evac-4m|ix|common|tph|lfb-32|nb-8192|incs-256000|sid-16  # 256M + 128K + evac (n=16, 4mb)
  # - jdk-lxr-rc-evac-4m|ix|common|tph|lfb-32|nb-8192|incs-256000|sid-4|sidm-8  # 256M + 128K + evac (n=4, 32mb)
  # - jdk-lxr-rc-evac-4m|ix|common|tph|lfb-32|nb-8192|incs-256000|sid-8|sidm-8  # 256M + 128K + evac (n=8, 32mb)
  # - jdk-lxr-rc-evac-4m|ix|common|tph|lfb-32|nb-8192|incs-256000|sid-16|sidm-8  # 256M + 128K + evac (n=16, 32mb)

  - jdk-lxr-rc-evac-4m|ix|common|tph|lfb-32|nb-8192|incs-512000|sid-4  # 256M + 128K + evac (n=4, 4mb)
  - jdk-lxr-rc-evac-4m|ix|common|tph|lfb-32|nb-8192|incs-512000|sid-8  # 256M + 128K + evac (n=8, 4mb)
  - jdk-lxr-rc-evac-4m|ix|common|tph|lfb-32|nb-8192|incs-512000|sid-16  # 256M + 128K + evac (n=16, 4mb)
  # - jdk-lxr-rc-evac-4m|ix|common|tph|lfb-32|nb-8192|incs-512000|sid-4|sidm-8  # 256M + 128K + evac (n=4, 32mb)
  # - jdk-lxr-rc-evac-4m|ix|common|tph|lfb-32|nb-8192|incs-512000|sid-8|sidm-8  # 256M + 128K + evac (n=8, 32mb)
  # - jdk-lxr-rc-evac-4m|ix|common|tph|lfb-32|nb-8192|incs-512000|sid-16|sidm-8  # 256M + 128K + evac (n=16, 32mb)