# running runbms ./evaluation/results/log ./evaluation/configs/lxr-modest-heap-conc/config.yml 8 4 8 --skip-oom 1 --skip-timeout 1 > ~/_log

includes:
  - "../common.yml"
  # - "../minheap.yml"

overrides:
  invocations: 20
  suites.dacapochopin-29a657f.timing_iteration: 5
  suites.dacapochopin-29a657f.minheap: g1
  benchmarks.dacapochopin-29a657f:
    - lusearch
    - cassandra
    - tomcat
    - h2

  # Can't run
    # - tradebeans
    # - tradesoap
    # - jme
    # - kafka

runtimes:
  jdk-lxr-stw-old:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-stw-old-{git}/jdk"
  jdk-lxr-stw:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-stw-{git}/jdk"
  jdk-lxr-old:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-old-{git}/jdk"
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-{git}/jdk"

plugins:
  dacapo-latency:
    type: CopyFile
    patterns:
      - "scratch/dacapo-latency-*.csv"

modifiers:
  nobarrier:
    type: EnvVar
    var: "BARRIER"
    val: "NoBarrier"
  nb:
    type: EnvVar
    var: "NURSERY_BLOCKS"
    val: "{0}"
  nr:
    type: EnvVar
    var: "NURSERY_RATIO"
    val: "{0}"
  noreuse:
    type: EnvVar
    var: "DISABLE_MUTATOR_LINE_REUSING"
    val: "1"
  mu:
    type: ProgramArg
    val: "-t {0}"
  latency:
    type: ProgramArg
    val: "--dump-latency"
  waitlazy:
    type: EnvVar
    var: "NO_GC_UNTIL_LAZY_SWEEPING_FINISHED"
    val: "1"
  nowaitlazy:
    type: EnvVar
    var: "NO_GC_UNTIL_LAZY_SWEEPING_FINISHED"
    val: "0"
  incs:
    type: EnvVar
    var: "INCS_LIMIT"
    val: "{0}"
  mevac:
    type: EnvVar
    var: "MAX_MATURE_DEFRAG_MB"
    val: "{0}"
  trace:
    type: EnvVar
    var: "TRACE_THRESHOLD"
    val: "{0}"
  oevac_threshold:
    type: EnvVar
    var: "OPPORTUNISTIC_EVAC_THRESHOLD"
    val: "{0}"
  oevac_enable:
    type: EnvVar
    var: "OPPORTUNISTIC_EVAC"
    val: "1"
  oevac:
    type: ModifierSet
    val: "oevac_enable|oevac_threshold-50"
  g1_default:
    type: JVMArg
    val: "-XX:+UseG1GC"

configs:
  - jdk-lxr|g1|common|hs_perf|latency
  - jdk-lxr|g1_default|common|hs_perf|latency
  - jdk-lxr-old|ix|common|tph|mmtk_perf|nr-1|latency
  - jdk-lxr|ix|common|tph|mmtk_perf|oevac|latency
  - jdk-lxr|shenandoah|common|hs_perf|latency
  - jdk-lxr|z|common|hs_perf|latency
