# running runbms ./evaluation/results/log ./evaluation/configs/lxr-modest-heap-conc/config.yml 8 4 8 --skip-oom 1 --skip-timeout 1 > ~/_log

includes:
  - "../common.yml"
  - "../lxr-modifiers.yml"

overrides:
  invocations: 20
  suites.dacapochopin-29a657f.timing_iteration: 5
  suites.dacapochopin-29a657f.minheap: g1
  benchmarks.dacapochopin-29a657f:
    - lusearch
    - cassandra
    - tomcat
    - h2
  # Can't run
    # - tradebeans
    # - tradesoap
    # - jme
    # - kafka

runtimes:
  jdk-lxr-stw-old:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-stw-old-cb38c7b0/jdk"
  jdk-lxr-stw:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-stw-{git}/jdk"
  jdk-lxr-old:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-old-{git}/jdk"
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-{git}/jdk"

plugins:
  dacapo-latency:
    type: CopyFile
    patterns:
      - "scratch/dacapo-latency-*.csv"

configs:
  - jdk-lxr|g1|common|hs_perf|latency
  - jdk-lxr|g1_default|common|hs_perf|latency
  # - jdk-lxr-old|ix|common|tph|mmtk_perf|nr-1|latency|cm-90
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|latency|defrag_ratio-20|rc_free_blocks-5|cm-90
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|latency|defrag_ratio-20|rc_free_blocks-5|cm-80
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|latency|defrag_ratio-20|rc_free_blocks-5|cm-70
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|latency|defrag_ratio-20|rc_free_blocks-5|cm-60
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|latency|defrag_ratio-10|rc_free_blocks-5
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|latency|defrag_ratio-20|rc_free_blocks-10
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|latency|defrag_ratio-30|rc_free_blocks-15
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|latency|defrag_ratio-10|rc_free_blocks-5
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|latency|defrag_ratio-20|rc_free_blocks-10
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|latency|defrag_ratio-30|rc_free_blocks-15

  - jdk-lxr-old|ix|common|tph|mmtk_perf|nr-1|latency|cm-90
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|latency|defrag_ratio-10|incs-10000|trace-10
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|latency|defrag_ratio-20|incs-10000|trace-10
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|latency|defrag_ratio-30|incs-10000|trace-10
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|latency|defrag_ratio-30|incs-10000|trace-20
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|latency|defrag_ratio-30|incs-10000|trace-30
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|latency|defrag_ratio-30|incs-5000|trace-10
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|latency|defrag_ratio-30|incs-15000|trace-10



  - jdk-lxr|ix|common|tph|mmtk_perf|oevac|latency|incs-15000|trace-10
  - jdk-lxr|ix|common|tph|mmtk_perf|oevac|latency|incs-15000|trace-20
  - jdk-lxr|ix|common|tph|mmtk_perf|oevac|latency|incs-15000|trace-30


  - jdk-lxr|ix|common|tph|mmtk_perf|oevac|latency|incs-10000|trace-10
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|latency|incs-15000|trace-10
  - jdk-lxr|ix|common|tph|mmtk_perf|oevac|latency|incs-20000|trace-10

  - jdk-lxr|shenandoah|common|hs_perf|latency
  - jdk-lxr|z|common|hs_perf|latency
