# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./_config.yml"


overrides:
  heap_range: 2
  configs:
    - jdk-lxr-rc|g1|common|hs
    - jdk-lxr-rc|ix|common|tph|lfb-32|nb-8192|incs-16000  # Incs 16K
    - jdk-lxr-rc|ix|common|tph|lfb-32|nb-8192|incs-32000  # Incs 32K
    - jdk-lxr-rc|ix|common|tph|lfb-32|nb-8192|incs-64000  # Incs 64K
    - jdk-lxr-rc|ix|common|tph|lfb-32|nb-8192|incs-128000  # Incs 128K
    - jdk-lxr-rc|ix|common|tph|lfb-32|nb-8192|incs-256000  # Incs 256K
    - jdk-lxr-rc|ix|common|tph|lfb-32|nb-8192|incs-512000  # Incs 512K
    - jdk-lxr-rc|ix|common|tph|lfb-32|nb-8192|incs-1024000  # Incs 1024K

