# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./_config.yml"


overrides:
  invocations: 20
  benchmarks.dacapochopin-29a657f:
    - lusearch
  configs:
    - jdk-lxr|g1|common|hs_perf|latency
    - jdk-lxr|shenandoah|common|hs_perf|latency|hs_cgc-21
