# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./_config.yml"


overrides:
  heap_range: 2
  benchmarks.dacapochopin-29a657f:
    - cassandra
    - tomcat
    - h2
  configs:
    - jdk-lxr|g1|common|hs_perf|latency
    - jdk-lxr|ix|common|tph|nr-1|latency
    - jdk-lxr|shenandoah|common|hs_perf|latency
    # - jdk-lxr|shenandoah|common|hs_perf|latency|hs_cgc-21
    - jdk-lxr|z|common|hs_perf|latency


