# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "../common.yml"
  - "../lxr-modifiers.yml"

overrides:
  heap_range: 6
  invocations: 20
  suites.dacapochopin-29a657f.minheap: adoptopenjdk-15-G1
  benchmarks.dacapochopin-29a657f:
    - lusearch
    - cassandra
    - tomcat
    - h2

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-{git}/jdk"
  jdk-rcix:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-rcix-{git}/jdk"
  jdk-ix:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-ix-{git}/jdk"

plugins:
  dacapo-latency:
    type: CopyFile
    patterns:
      - "scratch/dacapo-latency-*.csv"

configs:
  - jdk-lxr|g1_old|common|hs_perf|latency
  - jdk-lxr|g1_default|common|hs_perf|latency

  - jdk-ix|ix|common|tph|mmtk_perf|latency
  - jdk-rcix|ix|common|tph|mmtk_perf|latency
  - jdk-lxr|ix|common|tph|mmtk_perf|nr-1|latency

  - jdk-lxr|shenandoah|common|hs_perf|latency
  - jdk-lxr|z|common|hs_perf|latency
