hfac: 2x

includes:
  - $CONFIGS/common/common-lxr.yml

build_gc: LXR

overrides:
  heap_range: 3
  invocations: 40
  suites.dacapochopin.minheap: G1-n5

runtimes:
  jdk-lxr: &lxr
    type: OpenJDK
    release: 11
    home: $BUILDS/jdk-lxr/jdk-11.0.19
    commits:
      mmtk-core: 9d4dafdd85783ef0b03d03da8f36b0e74526fdf4
      mmtk-openjdk: 09f87beba0231e0e3cde4fdb254c275f5b7e704e
      openjdk: bc9669aaed
    features: mmtk/no_meta_counting
    pgo: true
  jdk-lxr-2: # 0.26.0
    <<: *lxr
    home: $BUILDS/jdk-lxr-2/jdk-11.0.19
    commits:
      mmtk-core: fe3430b1aa0b76b4998acf382c22f617d1e567a5
      mmtk-openjdk: 34a3bfa557a4652b04757ceb52856c13ccbc5803
      openjdk: bc9669aaed

configs:
  # G1
  - jdk-lxr|g1|common3|hs
  # LXR
  - jdk-lxr|lxr|common3|tph
  - jdk-lxr-2|lxr|common3|tph
