hfac: 2x

includes:
  - $CONFIGS/common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 20
  suites.dacapochopin.minheap: G1-n5

build_gc: LXR

runtimes:
  jdk-lxr: &lxr
    type: OpenJDK
    release: 11
    home: $BUILDS/jdk-lxr/jdk-11.0.19
    commits:
      mmtk-core: e1af7fc41cbee3e77ec75ce092efb5ae7f5e65ea
      mmtk-openjdk: 46546ed41d28dd101eb57dca5422b73148f6ee06
      openjdk: bc9669aaed
    features: mmtk/no_meta_counting
    pgo: true
  jdk-lxr-rebase: # 0.32.0
    <<: *lxr
    home: $BUILDS/jdk-lxr-2/jdk-11.0.19
    commits:
      mmtk-core: c1fb1c3c5393907234938349eeddcf0cb34c7d62
      mmtk-openjdk: a4e42fbc2644a8e41b90fa1effa524243fb29809
      openjdk: bc9669aaed

configs:
  # G1
  - jdk-lxr|g1|common3|hs
  # LXR
  - jdk-lxr|lxr|common3|tph|disable_thp
  - jdk-lxr-rebase|lxr|common3|tph|disable_thp
