hfac: 2x

includes:
  - $CONFIGS/common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 40
  suites.dacapochopin.minheap: G1-n5

runtimes:
  jdk-lxr: &lxr
    type: OpenJDK
    release: 11
    home: $BUILDS/jdk-lxr/jdk-11.0.19
    commits:
      mmtk-core: b41321c36dc659a29a3add93c4ad3e19e3f7e409
      mmtk-openjdk: f787e4bb55cf292e37a2ab14aae17d27b681fcf2
      openjdk: bc9669aaed
    features: mmtk/no_meta_counting
  jdk-lxr-2: # 0.26.0
    <<: *lxr
    home: $BUILDS/jdk-lxr-2/jdk-11.0.19
    commits:
      mmtk-core: abd73a8ea6f97d83fed1f95ba12ab89c6680c2b2
      mmtk-openjdk: 5f79679d2fb4573bdc8cdd4b9172f7dbc2d49bdb
      openjdk: bc9669aaed

configs:
  # G1
  - jdk-lxr|g1|common3|hs
  # LXR
  - jdk-lxr|lxr|common3|tph
  - jdk-lxr-2|lxr|common3|tph
