hfac: 2x

includes:
  - $CONFIGS/common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 20
  suites.dacapochopin.minheap: G1-n5

build_gc: LXR

runtimes:
  jdk-lxr: # 0.32.0
    <<: *lxr
    home: $BUILDS/jdk-lxr-2/jdk-11.0.19
    commits:
      mmtk-core: 8c17aa5cfd08a61865ff2afc75034ad4c5e4dd31
      mmtk-openjdk: a078ed046669b9a9f20f928f677c497d0879e97b
      openjdk: bc9669aaed

configs:
  # G1
  - jdk-lxr|g1|common3|hs
  # LXR
  - jdk-lxr|lxr|common3|tph|disable_thp
