# running runbms ./evaluation/results/log ./evaluation/configs/fb/config.yml 8 2 --skip-oom 1 --skip-timeout 1 > ~/_log

includes:
  - "../common.yml"

overrides:
  invocations: 20
  suites.dacapochopin-29a657f.minheap: immix
  benchmarks.dacapochopin-29a657f:
    - lusearch
    - h2
    # - tradebeans
    # - tradesoap
    - cassandra
    - tomcat
    - fop
    - h2o
    - avrora
    - batik
    - biojava
    - eclipse
    - graphchi
    # - jme
    - jython
    # - kafka
    - luindex
    - pmd
    - sunflow
    - xalan
    - zxing

runtimes:
  jdk:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/fb/jdk-{git}/jdk"

configs:
  - jdk|ix|barrier-NoBarrier|common|tph|probes_cp|probes|mmtk_perf|threads-1
  - jdk|ix|barrier-FieldBarrier|common|tph|probes_cp|probes|mmtk_perf|threads-1