# running runbms ./evaluation/results/log ./evaluation/configs/lxr-incs-n/config.yml 8 5 3 1 7 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "../common.yml"
  # - "../minheap.yml"

overrides:
  invocations: 5
  suites.dacapochopin-29a657f.minheap: immix-rc
  benchmarks.dacapochopin-29a657f:
    - fop
    - lusearch
    - h2o
    - avrora
    - batik
    - biojava
    - cassandra
    - eclipse
    - graphchi
    # - h2
    - jme
    - jython
    # - kafka
    - luindex
    - pmd
    - sunflow
    - tomcat
    # - tradebeans
    # - tradesoap
    - xalan
    - zxing

runtimes:
  jdk:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/lxr-incs-n/jdk-a36ff5bc/jdk"
  jdk-ins:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/lxr-incs-n/jdk-ins-a36ff5bc/jdk"

modifiers:
  nobarrier:
    type: EnvVar
    var: "BARRIER"
    val: "NoBarrier"
  nb:
    type: EnvVar
    var: "NURSERY_BLOCKS"
    val: "{0}"
  noreuse:
    type: EnvVar
    var: "DISABLE_MUTATOR_LINE_REUSING"
    val: "1"

configs:
  - jdk|ix|common|tph|mmtk_perf|nb-512 # 16M Nursery
  - jdk|ix|common|tph|mmtk_perf|nb-1024 # 32M Nursery
  - jdk|ix|common|tph|mmtk_perf|nb-2048 # 64M Nursery
  - jdk|ix|common|tph|mmtk_perf|nb-4096 # 128M Nursery
  - jdk-ins|ix|common|tph|mmtk_perf|nb-512 # 16M Nursery
  - jdk-ins|ix|common|tph|mmtk_perf|nb-1024 # 32M Nursery
  - jdk-ins|ix|common|tph|mmtk_perf|nb-2048 # 64M Nursery
  - jdk-ins|ix|common|tph|mmtk_perf|nb-4096 # 128M Nursery