# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "../common.yml"
  - "../lxr-modifiers.yml"

overrides:
  heap_range: 3
  invocations: 5
  suites.dacapochopin-29a657f.minheap: g1
  benchmarks.dacapochopin-29a657f:
    - lusearch
    - h2
    - cassandra
    - tomcat
    - fop
    - h2o
    - avrora
    - batik
    - biojava
    - eclipse
    - graphchi
    - jython
    - luindex
    - pmd
    - sunflow
    - xalan
    - zxing

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-{git}/jdk"

configs:
  - jdk-lxr|g1|common|hs_pauses
  - jdk-lxr|ix|common|tph|trace2-5|srv-128|srvw|lfb-32

plugins:
  dacapo-latency:
    type: CopyFile
    patterns:
      - "scratch/pauses.csv"