# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "../common.yml"
  - "../lxr-modifiers.yml"

overrides:
  invocations: 10
  suites.dacapochopin-29a657f.minheap: huge
  benchmarks.dacapochopin-29a657f:
    - lusearch
    - cassandra
    - tomcat
    - h2
    - fop
    - h2o
    - avrora
    - batik
    - biojava
    - eclipse
    - graphchi
    - jython
    - luindex
    - pmd
    - sunflow
    - xalan
    - zxing

runtimes:
  jdk-lxr-rc-ins:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-rc-ins-{git}/jdk"
  jdk-lxr-rc:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-rc-{git}/jdk"

configs:
  - jdk-lxr-rc-ins|ix|common|tph|lfb-32|nb-1024
  - jdk-lxr-rc|ix|common|tph|lfb-32|nb-16384
