# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "../common-lxr.yml"

overrides:
  heap_range: 3
  invocations: 5
  suites.dacapochopin-6e411f33.minheap: g1

modifiers:
  lxr:
    type: EnvVar
    var: "MMTK_PLAN"
    val: "LXR"

runtimes:
  jdk-clsunload:
    type: OpenJDK
    release: 11
    home: /home/wenyuz/MMTk-Dev/evaluation/builds/jdk-mmtk-clsunload-6ea97091/jdk-11.0.15

configs:
  - jdk-clsunload|lxr|common2|defeature3|tph|trace2-20
  - jdk-clsunload|ix|common2|defeature3|tph