# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "../common-lxr.yml"

overrides:
  heap_range: 3
  invocations: 10
  suites.dacapochopin-6e411f33.minheap: g1
  benchmarks.dacapochopin-6e411f33:
    - cassandra

modifiers:
  lxr:
    type: EnvVar
    var: "MMTK_PLAN"
    val: "LXR"
  lxr_pldi:
    type: EnvVar
    var: "MMTK_PLAN"
    val: "Immix"

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: /home/wenyuz/MMTk-Dev/evaluation/builds/jdk-mmtk-lxr-ad1f18c88/jdk-11.0.15

configs:
  # - jdk-lxr|g1|common|defeature|hs

  # - jdk-lxr|g1|common|defeature2|hs
  - jdk-lxr|lxr|common|defeature2|tph|trace2-5
  # - jdk-lxr|lxr|common|defeature2|tph|trace2-10
  # - jdk-lxr|lxr|common|defeature2|tph|trace2-30
  # - jdk-lxr|lxr|common|defeature2|tph|trace2-50

  # - jdk-lxr|g1|common|defeature2|hs
  # - jdk-lxr|g1|common|defeature2|hs|no_prefetch

  # - jdk-lxr|lxr|common|defeature2|tph|trace2-20|no_prefetch           # Baseline (Prefetch)
  # - jdk-lxr|lxr|common|defeature2|tph|trace2-20                       # No Prefetch
  # - jdk-lxr-zero|lxr|common|defeature2|tph|trace2-20                  # Zeroing
  # - jdk-lxr-alloc-fix|lxr|common|defeature2|tph|trace2-20             # Large TLAB

  # - jdk-lxr|ix|common|defeature2|tph|trace2-20|no_prefetch           # Baseline (Prefetch)
  # - jdk-lxr|ix|common|defeature2|tph|trace2-20                       # No Prefetch
  # - jdk-lxr-zero|ix|common|defeature2|tph|trace2-20                  # Zeroing
  # - jdk-lxr-alloc-fix|ix|common|defeature2|tph|trace2-20             # Large TLAB

  # - jdk-lxr|ss|common|defeature2|tph|trace2-20|no_prefetch           # Baseline (Prefetch)
  # - jdk-lxr|ss|common|defeature2|tph|trace2-20                       # No Prefetch
  # - jdk-lxr-zero|ss|common|defeature2|tph|trace2-20                  # Zeroing

  # - jdk-lxr-alloc-fix|ss|common|defeature2|tph|trace2-20             # Large TLAB


  # - jdk-lxr|ix|common|defeature2|tph|trace2-20
  # - jdk-lxr|ix|common|defeature2|tph|trace2-20|no_prefetch
  # - jdk-lxr-alloc-fix|ix|common|defeature2|tph|trace2-20

  # - jdk-lxr|ss|common|defeature2|tph|trace2-20
  # - jdk-lxr|ss|common|defeature2|tph|trace2-20|no_prefetch
  # - jdk-lxr-alloc-fix|ss|common|defeature2|tph|trace2-20

  # - jdk-lxr|lxr|common|defeature|tph
  # - jdk-lxr|lxr|common|defeature2|tph|trace2-5
  # - jdk-lxr|lxr|common|defeature2|tph|trace2-20
  # - jdk-lxr-alloc-fix|lxr|common|defeature2|tph|trace2-20
  # - jdk-lxr|lxr|common|defeature2|tph|trace2-20
  # - jdk-lxr|lxr|common|defeature2|tph|trace2-30
  # - jdk-lxr|ss|common|defeature2|tph
  # - jdk-lxr-alloc-fix|ss|common|defeature2|tph

  # - jdk-lxr|ix|common|defeature2|tph
  # - jdk-lxr-alloc-fix|ix|common|defeature2|tph

  # - jdk-lxr-pldi|lxr_pldi|common|defeature|tph|trace2-5|srv-128|srvw|lfb-32
  # - jdk-lxr-pldi-exploded|lxr_pldi|common|defeature|tph|trace2-5|srv-128|srvw|lfb-32

  # - jdk-lxr|shenandoah|common|defeature2|hs
  # - jdk-lxr|z|common|defeature2|hs
