includes:
  - "/home/wenyuz/MMTk-Dev/running-ng/config/base/runbms.yml"

benchmarks:
  dacapochopin-69a704e:
    # - avrora
    - batik
    - biojava
    - xalan
    #- cassandra
    #- eclipse
    #- fop
    - graphchi
    - h2
    - h2o
    - jme

overrides:
  "suites.dacapochopin-69a704e.timing_iteration": 5
  "suites.dacapochopin-69a704e.callback": "probe.DacapoChopinCallback"
  "suites.dacapochopin-69a704e.timeout": 600

runtimes:
  nobarrier:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/flb/jdk-immix-cm-nobarrier/jdk"
  fieldlogging_iu:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/flb/jdk-immix-cm-fieldlogging-iu/jdk"
  fieldlogging_satb:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/flb/jdk-immix-cm-fieldlogging-satb/jdk"

modifiers:
  probes_cp:
    type: JVMClasspath
    val: "/home/wenyuz/MMTk-Dev/evaluation/probes /home/wenyuz/MMTk-Dev/evaluation/probes/probes.jar"
  probes:
    type: JVMArg
    val: "-Djava.library.path=/home/wenyuz/MMTk-Dev/evaluation/probes -Dprobes=RustMMTk"

configs:
  - "nobarrier|ms|s|c2|mmtk_gc-Immix|tph|probes_cp|probes"
  - "fieldlogging_iu|ms|s|c2|mmtk_gc-Immix|tph|probes_cp|probes"
  - "fieldlogging_satb|ms|s|c2|mmtk_gc-Immix|tph|probes_cp|probes"