# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./common/common-lxr.yml"

overrides:
  heap_range: 3
  invocations: 20
  suites.dacapochopin.minheap: G1
  benchmarks.dacapochopin:
    - lusearch
    - cassandra
    - h2
    - spring
    - tradebeans
    - tradesoap
    - avrora
    - biojava
    - eclipse
    - graphchi
    - h2o
    - kafka
    - luindex
    - pmd
    - sunflow
    - xalan

runtimes:
  jdk-mmtk-global-fifo:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk/jdk-11.0.19
    commits:
      mmtk-core: d36d3611f
      mmtk-openjdk: e8cf5aaa08
      openjdk: bc9669aaed
    features: mmtk/perf_counter,mmtk/buf_1024
  jdk-mmtk-global-lifo:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lifo/jdk-11.0.19
    commits:
      mmtk-core: d36d3611f
      mmtk-openjdk: e8cf5aaa08
      openjdk: bc9669aaed
    features: mmtk/perf_counter,mmtk/buf_1024,mmtk/lifo
  jdk-mmtk-local-fifo:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-local-fifo/jdk-11.0.19
    commits:
      mmtk-core: d36d3611f
      mmtk-openjdk: e8cf5aaa08
      openjdk: bc9669aaed
    features: mmtk/perf_counter,mmtk/buf_1024,mmtk/local
  jdk-mmtk-local-lifo:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-local-lifo/jdk-11.0.19
    commits:
      mmtk-core: d36d3611f
      mmtk-openjdk: e8cf5aaa08
      openjdk: bc9669aaed
    features: mmtk/perf_counter,mmtk/buf_1024,mmtk/local,mmtk/lifo

configs:
  - jdk-mmtk-global-fifo|ix|common3|ms|tph_perf
  - jdk-mmtk-global-lifo|ix|common3|ms|tph_perf
  - jdk-mmtk-local-fifo|ix|common3|ms|tph_perf
  - jdk-mmtk-local-lifo|ix|common3|ms|tph_perf
