# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./common/common-lxr.yml"

overrides:
  heap_range: 3
  invocations: 20
  suites.dacapochopin.minheap: G1

runtimes:
  jdk-lxr-pldi: &lxr-pldi
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-lxr-pldi/jdk-11.0.11
    commits:
      mmtk-core: 4d4e516
      mmtk-openjdk: f933db31a
      openjdk: f817e9d00b
    features: lxr,lxr_heap_health_guided_gc
    test-command: MMTK_PLAN=Immix TRACE_THRESHOLD2=10 LOCK_FREE_BLOCKS=32 MAX_SURVIVAL_MB=256 SURVIVAL_PREDICTOR_WEIGHTED=1 ./openjdk/build/linux-x86_64-normal-server-release/images/jdk/bin/java -XX:MetaspaceSize=1G -XX:-UseBiasedLocking -XX:-TieredCompilation -XX:+UnlockDiagnosticVMOptions -XX:-InlineObjectCopy -Djava.library.path=./evaluation/probes -cp ./evaluation/probes:./evaluation/probes/probes.jar:/home/wenyuz/dacapo/dacapo-evaluation-git-b00bfa9.jar -XX:+UseThirdPartyHeap -Dprobes=RustMMTk -Xms100M -Xmx100M Harness -n 5 -c probe.DacapoChopinCallback lusearch
  jdk-lxr-latest-defeatured: &lxr-latest
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-lxr-latest-defeatured/jdk-11.0.19
    commits:
      mmtk-core: 8f76a350
      mmtk-openjdk: e0b27083
      openjdk: bc9669aaed
    features: no_weak_refs

configs:
  # G1
  - jdk-lxr-latest-defeatured|g1|common_defeature|hs
  - jdk-lxr-pldi|g1|common_defeature|hs
  # LXR
  - jdk-lxr-latest-defeatured|lxr|common_defeature|tph
  - jdk-lxr-pldi|ix|common_defeature|tph|trace2-5|srv-128|srvw|lfb-32
