# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./common/common-lxr.yml"

overrides:
  heap_range: 3
  invocations: 20
  suites.dacapochopin-04132797.minheap: G1

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr/jdk-11.0.19
    commits:
      mmtk-core: 333ffb8
      mmtk-openjdk: 98eb6f9
      openjdk: 7caf8f7d
  jdk-lxr-merge:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-merge/jdk-11.0.19
    commits:
      mmtk-core: 1fad03d2
      mmtk-openjdk: 9e6214a
      openjdk: 7caf8f7d
  jdk-lxr-merge-revert:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-merge-revert/jdk-11.0.19
    commits:
      mmtk-core: 8228e5e5
      mmtk-openjdk: 9e6214a
      openjdk: 7caf8f7d

configs:
  - jdk-lxr|lxr|common3|tph
  - jdk-lxr-merge|lxr|common3|tph
  - jdk-lxr-merge-revert|lxr|common3|tph
