# ./evaluation/manager run --config lzr-finalizer --hfac 2x

includes:
  - "./common/common-lxr.yml"

overrides:
  heap_range: 3
  invocations: 20
  suites.dacapochopin.minheap: G1
runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-lxr/jdk-11.0.19
    commits:
      mmtk-core: dc332e82a79
      mmtk-openjdk: 2cf7c70a63
      openjdk: 7caf8f7d
  jdk-lxr-fix-finalizer:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-lxr-fix-finalizer/jdk-11.0.19
    commits:
      mmtk-core: dc332e82a79
      mmtk-openjdk: 2cf7c70a63
      openjdk: bc9669aaedc

configs:
  - jdk-lxr|lxr|common3|tph
  - jdk-lxr-fix-finalizer|lxr|common3|tph
