includes:
  - ./common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 40
  suites.dacapochopin-0d047f55.minheap: g1

runtimes:
  jdk-lxr-coops:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-coops/jdk-11.0.19
    commits:
      mmtk-core: e8028d1
      mmtk-openjdk: d8fd433
      openjdk: 91259ca
  jdk-lxr-coops2:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-coops2/jdk-11.0.19
    commits:
      mmtk-core: 13fe8b6
      mmtk-openjdk: 55d9080
      openjdk: 91259ca

configs:
  - jdk-lxr-coops|lxr|common3|tph
  - jdk-lxr-coops2|lxr|common3|tph
  - jdk-lxr-coops|lxr|common3|tph|no_compressed_oops
  - jdk-lxr-coops2|lxr|common3|tph|no_compressed_oops
  