includes:
  - ./common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 20

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr/jdk-11.0.19
    commits:
      mmtk-core: a0d61e8
      mmtk-openjdk: d048758
      openjdk: 91259ca

configs:
  - jdk-lxr|g1|common3|hs
  - jdk-lxr|lxr|common3|tph
  