# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./common/common-lxr.yml"

overrides:
  heap_range: 3
  invocations: 20
  suites.dacapochopin-rc3.minheap: G1

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr/jdk-11.0.19
    commits:
      mmtk-core: c1eda8edea8
      mmtk-openjdk: 4bbae7ad910
      openjdk: 7caf8f7d
  jdk-lxr-plm0:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-lxr-plm0/jdk-11.0.19
    commits:
      mmtk-core: c1eda8edea8
      mmtk-openjdk: 4bbae7ad910
      openjdk: 7caf8f7d
    features: mmtk/perf_counter_plm0

configs:
  - jdk-lxr|g1|common3|hs_perf
  - jdk-lxr|lxr|common3|tph_perf
  - jdk-lxr|lxr|common3|tph_perf|threads-6
  - jdk-lxr-plm0|g1|common3|hs_perf0
  - jdk-lxr-plm0|lxr|common3|tph_perf
  - jdk-lxr-plm0|lxr|common3|tph_perf|threads-6
