includes:
  - ./common/common-lxr.yml

overrides:
  heap_range: 8
  invocations: 20
  suites.dacapochopin-rc3.minheap: G1
  benchmarks.dacapochopin-rc3:
    - spring
    - h2
    - lusearch

runtimes:
  jdk-mmtk-pfm-fix:
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-mmtk-pfm-fix/jdk-11.0.19
    commits:
      mmtk-core: 760f081b5
      mmtk-openjdk: 60a8357182
      openjdk: 28e56ee325

modifiers:
  mmtk_perf:
    type: EnvVar
    var: "MMTK_PHASE_PERF_EVENTS"
    val: "PERF_COUNT_SW_TASK_CLOCK,0,-1;PERF_COUNT_HW_CPU_CYCLES,0,-1;PERF_COUNT_HW_INSTRUCTIONS,0,-1;PERF_COUNT_HW_CACHE_L1D:MISS,0,-1;PERF_COUNT_HW_CACHE_DTLB:MISS,0,-1"
  exclude_kernel:
    type: EnvVar
    var: "MMTK_PERF_EXCLUDE_KERNEL"
    val: "true"

configs:
  - jdk-mmtk-pfm-fix|g1|ms|common3|hs_perf
  - jdk-mmtk-pfm-fix|g1|ms|common3|hs_perf0
  - jdk-mmtk-pfm-fix|ss|ms|common3|tph|mmtk_perf
  - jdk-mmtk-pfm-fix|ss|ms|common3|tph|mmtk_perf|exclude_kernel
