# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "../common.yml"
  - "../lxr-modifiers.yml"

overrides:
  heap_range: 15
  invocations: 20
  suites.dacapochopin-29a657f.minheap: 1g
  benchmarks.dacapochopin-29a657f:
    - luindex
    - pmd
    - lusearch
    # - tradebeans
    # - tradesoap
    - cassandra
    - tomcat
    - h2
    - fop
    - h2o
    - avrora
    - batik
    - biojava
    - eclipse
    - graphchi
    # - jme
    - jython
    # - kafka
    - sunflow
    - xalan
    - zxing

runtimes:
  jdk-gencopy:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-gencopy-{git}/jdk"

configs:
  - jdk-gencopy|gencopy|common_noxcomp|tph

