# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "../common.yml"
  - "../lxr-modifiers.yml"

overrides:
  heap_range: 3
  invocations: 10
  suites.dacapochopin-29a657f.minheap: g1
  # suites.dacapochopin-29a657f.minheap: adoptopenjdk-15-G1
  benchmarks.dacapochopin-29a657f:
    - fop
    - lusearch
    # - tradebeans
    # - tradesoap
    - cassandra
    - tomcat
    - h2
    - h2o
    - avrora
    - batik
    - biojava
    - eclipse
    - graphchi
    # - jme
    - jython
    # - kafka
    - luindex
    - pmd
    - sunflow
    - xalan
    - zxing

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-{git}/jdk"

configs:
  - jdk-lxr|g1|common|hs
  - jdk-lxr|ix|common|tph
  - jdk-lxr|shenandoah|common|hs
  - jdk-lxr|z|common|hs

  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|incs-15000|trace-10
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|incs-15000|trace-20
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|incs-15000|trace-30


  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|incs-10000|trace-10
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|incs-15000|trace-10
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|incs-20000|trace-10

  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|defrag_ratio-20|incs-10000|trace-10
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|defrag_ratio-30|incs-10000|trace-10
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|defrag_ratio-30|incs-10000|trace-20
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|defrag_ratio-30|incs-10000|trace-30
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|defrag_ratio-30|incs-5000|trace-10
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|defrag_ratio-30|incs-15000|trace-10

  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|defrag_ratio-10|incs-15000|trace-30

  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|defrag_ratio-20
  # - jdk-lxr-stw|ix|common|tph|mmtk_perf|oevac|defrag_ratio-20
  # G1
  # - jdk-lxr-old|g1_default|common|hs_perf
  # Different G1 builds
  # - jdk-lxr-stw-2022-03|g1_default|common|hs_perf
  # - jdk-lxr-stw-2021-11|g1_2021_11|common|hs_perf
  # - jdk-lxr-stw|g1_nocompressoops|common|hs_perf
  # - jdk-lxr-stw|g1_noclassunload|common|hs_perf
  # - jdk-lxr-stw|g1_noweakref|common|hs_perf
