# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "../common.yml"
  - "../lxr-modifiers.yml"

overrides:
  heap_range: 3
  invocations: 10
  suites.dacapochopin-29a657f.minheap: g1
  # suites.dacapochopin-29a657f.minheap: adoptopenjdk-15-G1
  benchmarks.dacapochopin-29a657f:
    - fop
    - lusearch
    # - tradebeans
    # - tradesoap
    - cassandra
    - tomcat
    - h2
    - h2o
    - avrora
    - batik
    - biojava
    - eclipse
    - graphchi
    # - jme
    - jython
    # - kafka
    - luindex
    - pmd
    - sunflow
    - xalan
    - zxing

runtimes:
  jdk-lxr-kc:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-kc-74635c46/jdk"
  jdk-lxr-new-trigger:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-new-trigger-0c8e76b6/jdk"
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-{git}/jdk"
  jdk-lxr-1m:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-1m-{git}/jdk"

configs:
  - jdk-lxr|g1|common|hs
  - jdk-lxr-new-trigger|ix|common|tph|incs-256000|trace-40
  - jdk-lxr|ix|common|tph|oevac-20|id|incs-256000|trace-40|defrag_thold-50

  - jdk-lxr|ix|common|tph|oevac-80|id|incs-256000|trace-40|defrag_thold-50
  - jdk-lxr-1m|ix|common|tph|oevac-20|id|incs-256000|trace-40|defrag_thold-50
  - jdk-lxr|ix|common|tph|oevac-20|id|incs-256000|trace-40|defrag_thold-50|region_rank
  - jdk-lxr|ix|common|tph|oevac-20|id|incs-256000|trace-40|defrag_thold-50|block_holes_rank

  - jdk-lxr|ix|common|tph|oevac-20|id|incs-256000|defrag_thold-50|mo-50|rc_after_satb-2
  - jdk-lxr|ix|common|tph|oevac-20|id|incs-256000|defrag_thold-50|mo-70|rc_after_satb-2
  - jdk-lxr|ix|common|tph|oevac-20|id|incs-256000|defrag_thold-50|mo-90|rc_after_satb-2
  - jdk-lxr|ix|common|tph|oevac-20|id|incs-256000|defrag_thold-50|mo-50|rc_after_satb-4
  - jdk-lxr|ix|common|tph|oevac-20|id|incs-256000|defrag_thold-50|mo-70|rc_after_satb-4
  - jdk-lxr|ix|common|tph|oevac-20|id|incs-256000|defrag_thold-50|mo-90|rc_after_satb-4



  # - jdk-lxr-kc|ix|common|tph|nr-1
  # - jdk-lxr-old|ix|common|tph|nr-1
  # - jdk-lxr-new-trigger|ix|common|tph|incs-256000|trace-60
  # - jdk-lxr-new-evac|ix|common|tph|oevac-20|id|incs-256000|trace-40|defrag_thold-30
  # - jdk-lxr-new-evac|ix|common|tph|oevac-20|id|incs-256000|trace-60|defrag_thold-30

  # - jdk-lxr|ix|common|tph|evac_all|incs-256000|trace-40|defrag_thold-10
  # - jdk-lxr|ix|common|tph|evac_all|incs-256000|trace-40|defrag_thold-20
  # - jdk-lxr|ix|common|tph|evac_all|incs-256000|trace-40|defrag_thold-40
  # - jdk-lxr|ix|common|tph|evac_all|incs-256000|trace-40|defrag_thold-50

  # - jdk-lxr|ix|common|tph|oevac-20|id|incs-256000|trace-40|defrag_thold-10
  # - jdk-lxr|ix|common|tph|oevac-20|id|incs-256000|trace-40|defrag_thold-20
  # - jdk-lxr|ix|common|tph|oevac-20|id|incs-256000|trace-40|defrag_thold-40

  # - jdk-lxr|ix|common|tph|incs-256000|trace-40|defrag_thold-50
  # - jdk-lxr|ix|common|tph|incs-256000|trace-20|defrag_thold-50

  # - jdk-lxr-old|shenandoah|common|hs
  # - jdk-lxr-old|z|common|hs

  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|incs-15000|trace-10
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|incs-15000|trace-20
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|incs-15000|trace-30


  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|incs-10000|trace-10
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|incs-15000|trace-10
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|incs-20000|trace-10

  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|defrag_ratio-20|incs-10000|trace-10
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|defrag_ratio-30|incs-10000|trace-10
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|defrag_ratio-30|incs-10000|trace-20
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|defrag_ratio-30|incs-10000|trace-30
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|defrag_ratio-30|incs-5000|trace-10
  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|defrag_ratio-30|incs-15000|trace-10

  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|defrag_ratio-10|incs-15000|trace-30

  # - jdk-lxr|ix|common|tph|mmtk_perf|oevac|defrag_ratio-20
  # - jdk-lxr-stw|ix|common|tph|mmtk_perf|oevac|defrag_ratio-20
  # G1
  # - jdk-lxr-old|g1_default|common|hs_perf
  # Different G1 builds
  # - jdk-lxr-stw-2022-03|g1_default|common|hs_perf
  # - jdk-lxr-stw-2021-11|g1_2021_11|common|hs_perf
  # - jdk-lxr-stw|g1_nocompressoops|common|hs_perf
  # - jdk-lxr-stw|g1_noclassunload|common|hs_perf
  # - jdk-lxr-stw|g1_noweakref|common|hs_perf
