# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./_config.yml"

overrides:
  configs:
    - jdk-lxr|g1|common|hs
    - jdk-lxr-new-trigger-2-e14de41b|ix|common|tph|trace2-10|srv-128|srvw|lfb-32
    - jdk-lxr-new-trigger-2-e14de41b|ix|common|tph|trace2-10|srv-128|srvw|lfb-32|maxcp-4096
    - jdk-lxr|ix|common|tph|trace2-15|defrag_thold-50|srv-128|srvw|lfb-32|maxcp-4096|oevac-60|id
    - jdk-lxr|shenandoah|common|hs

