# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "../common-lxr.yml"

overrides:
  heap_range: 3
  invocations: 20
  suites.dacapochopin-29a657f.minheap: g1

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/builds/jdk-lxr-a24d2a3b/jdk"

configs:
  - jdk-lxr|g1|common|hs
  - jdk-lxr|lxr|common|tph|trace2-5|srv-128|srvw|lfb-32
  - jdk-lxr|shenandoah|common|hs
  - jdk-lxr|z|common|hs
