# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "../common.yml"
  - "../lxr-modifiers.yml"

overrides:
  invocations: 10
  suites.dacapochopin-29a657f.minheap: g1
  benchmarks.dacapochopin-29a657f:
    - fop
    - lusearch
    # - tradebeans
    # - tradesoap
    - cassandra
    - h2o
    - avrora
    - batik
    - biojava
    - eclipse
    - graphchi
    - h2
    # - jme
    - jython
    # - kafka
    - luindex
    - pmd
    - sunflow
    - tomcat
    - xalan
    - zxing

runtimes:
  jdk-lxr-stw:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-stw-{git}/jdk"
  jdk-lxr-lazy:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-lazy-{git}/jdk"
  jdk-lxr-cm:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-cm-{git}/jdk"
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-{git}/jdk"

configs:
  - jdk-lxr|g1|common|hs_perf
  - jdk-lxr-stw|ix|common|tph|nr-1
  - jdk-lxr-lazy|ix|common|tph|nr-1
  - jdk-lxr-cm|ix|common|tph|nr-1
  - jdk-lxr|ix|common|tph|nr-1