#!/usr/bin/env python3

import os

advice_dir = '../running/advice'

all_files = [ f for f in os.listdir(advice_dir) if os.path.isfile(os.path.join(advice_dir, f)) ]

for file in all_files:
    ext = file[-3:]
    bm = file[:file.index('.')]
    new_file = f'{bm}{ext}'
    print(f'{file} -> {new_file}')
    os.rename(os.path.join(advice_dir, file), os.path.join(advice_dir, new_file))