# running runbms ./evaluation/results/log ./evaluation/configs/lxr-ins/config.yml 8 1 3 5 7 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "../common.yml"
  # - "../minheap.yml"

overrides:
  invocations: 3
  suites.dacapochopin-29a657f.minheap: adoptopenjdk-15-G1
  benchmarks.dacapochopin-29a657f:
    - cassandra
    - lusearch
    - pmd
    - fop
    - eclipse
    - h2o
    - avrora
    - batik
    - biojava
    - tomcat
    - h2
    - graphchi
    - jython
    - luindex
    - sunflow
    - xalan
    - zxing

runtimes:
  jdk:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-{git}/jdk"
  jdk-stw:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-stw-{git}/jdk"

modifiers:
  nobarrier:
    type: EnvVar
    var: "BARRIER"
    val: "NoBarrier"
  nb:
    type: EnvVar
    var: "NURSERY_BLOCKS"
    val: "{0}"
  noreuse:
    type: EnvVar
    var: "DISABLE_MUTATOR_LINE_REUSING"
    val: "1"
  nr:
    type: EnvVar
    var: "NURSERY_RATIO"
    val: "{0}"

configs:
  # - jdk-stw|ix|common|tph|mmtk_perf|nr-1
  - jdk|ix|common|tph|mmtk_perf|nr-1