# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "../common.yml"

overrides:
  heap_range: 6
  invocations: 10
  suites.dacapochopin-29a657f.minheap: immix

runtimes:
  jdk-mmtk-master:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/builds/jdk-mmtk-f0fed5fc0-master/jdk"
  jdk-mmtk-blockpr:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/builds/jdk-mmtk-ccd8e3deb-blockpr/jdk"

configs:
  - jdk-mmtk-master|ix|common|tph_perf
  - jdk-mmtk-blockpr|ix|common|tph_perf
