hfac: 2x

includes:
  - $CONFIGS/common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 20
  suites.dacapochopin.minheap: G1

runtimes:
  jdk-lxr-no-opt: &base-cfg
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-lxr-no-opt/jdk-11.0.19
    commits:
      mmtk-core: c9977c11db2ce4553dc3d060fb6fd6e07c8fab6d # lxr-no-cmopt
      mmtk-openjdk: 46f70a5da616b4980ef5f7bb85ede21fe316dc60
      openjdk: bc9669aaed
    features: mmtk/no_meta_counting
  jdk-lxr-opt-mark:
    <<: *base-cfg
    home: /$BUILDS/jdk-lxr-opt-mark/jdk-11.0.19
    features: mmtk/opt_attempt_mark,mmtk/no_meta_counting
  jdk-lxr-opt-space-check:
    <<: *base-cfg
    home: /$BUILDS/jdk-lxr-opt-space-check/jdk-11.0.19
    features: mmtk/opt_space_check,mmtk/no_meta_counting
  jdk-lxr-no-dyn-dispatch:
    <<: *base-cfg
    home: /$BUILDS/jdk-lxr-no-dyn-dispatch/jdk-11.0.19
    features: mmtk/no_dyn_dispatch,mmtk/no_meta_counting
  jdk-lxr-opt-rc-check:
    <<: *base-cfg
    home: /$BUILDS/jdk-lxr-opt-rc-check/jdk-11.0.19
    features: mmtk/fast_rc_check,mmtk/no_meta_counting
  jdk-lxr-edge-enqueuing:
    <<: *base-cfg
    home: /$BUILDS/jdk-lxr-edge-enqueuing/jdk-11.0.19
    features: mmtk/edge_enqueuing,mmtk/no_meta_counting
  jdk-lxr-opt:
    <<: *base-cfg
    home: /$BUILDS/jdk-lxr-opt/jdk-11.0.19
    features: mmtk/opt,mmtk/no_meta_counting

configs:
  # LXR
  - jdk-lxr-no-opt|lxr|common3|tph
  - jdk-lxr-opt-mark|lxr|common3|tph
  - jdk-lxr-opt-space-check|lxr|common3|tph
  - jdk-lxr-no-dyn-dispatch|lxr|common3|tph
  - jdk-lxr-opt-rc-check|lxr|common3|tph
  - jdk-lxr-skip-marked|lxr|common3|tph
  - jdk-lxr-edge-enqueuing|lxr|common3|tph
  - jdk-lxr-opt|lxr|common3|tph
