hfac: 2x

includes:
  - $CONFIGS/common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 20
  suites.dacapochopin.minheap: G1

runtimes:
  jdk-lxr: &lxr
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-lxr/jdk-11.0.19
    commits: &lxr-commits
      mmtk-core: 8f76a3501
      mmtk-openjdk: 46f70a5da6
      openjdk: bc9669aaed
    features: mmtk/no_meta_counting
  jdk-lxr-no-weak-processor-opt:
    <<: *lxr
    home: /$BUILDS/jdk-lxr-no-weak-processor-opt/jdk-11.0.19
    commits:
      <<: *lxr-commits
      mmtk-openjdk: 85d3d7834

configs:
  - jdk-lxr|lxr|common|tph
  - jdk-lxr-no-weak-processor-opt|lxr|common|tph
