hfac: 2x

includes:
  - $CONFIGS/common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 20
  suites.dacapochopin.minheap: G1

runtimes:
  jdk-lxr: &lxr
    type: OpenJDK
    release: 11
    home: /$BUILDS/jdk-lxr/jdk-11.0.19
    commits:
      mmtk-core: 8f76a35015aeeb9da6172a4d0f834e1649153da4
      mmtk-openjdk: 46f70a5da616b4980ef5f7bb85ede21fe316dc60
      openjdk: bc9669aaed
  jdk-lxr-jul2023:
    <<: *lxr
    home: /$BUILDS/jdk-lxr-jul2023/jdk-11.0.19
    commits:
      mmtk-core: ad9314e
      mmtk-openjdk: 98eb6f9f
      openjdk: bc9669aaed

configs:
  # G1
  - jdk-lxr|g1|common3|hs
  - jdk-lxr|shenandoah|common3|hs
  - jdk-lxr|z|common3|hs
  # LXR
  - jdk-lxr|lxr|common3|tph
  - jdk-lxr-jul2023|lxr|common3|tph
