hfac: 2x

includes:
  - $CONFIGS/common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 3
  suites.dacapochopin.minheap: Immix
  benchmarks.dacapochopin:
    - lusearch
    - h2
    - cassandra
    - tomcat
    - spring
    - tradebeans
    - tradesoap
    - kafka

    - avrora
    # - batik
    - biojava
    # - eclipse
    - fop
    - graphchi
    - h2o
    - jme
    - jython
    - luindex
    - pmd
    - sunflow
    - xalan
    - zxing

runtimes:
  jdk-lxr: &lxr
    type: OpenJDK
    release: 11
    home: $BUILDS/jdk-lxr/jdk-11.0.19
    commits:
      mmtk-core: adaf2516d0d7fb75ad2844746ad81575cd0b77e7
      mmtk-openjdk: 09f87beba0231e0e3cde4fdb254c275f5b7e704e
      openjdk: bc9669aaedc07924d08b939adedcad33f3e76065
    features: mmtk/no_meta_counting,instrumentation

configs:
  - jdk-lxr|lxr|common3|tph
