hfac: 2x

includes:
  - $CONFIGS/common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 20
  suites.dacapochopin.minheap: G1-n5
  benchmarks.dacapochopin:
    - tradebeans
    - tradesoap
    - jython

build_gc: LXR

runtimes:
  jdk-lxr: &lxr # 0.32.0
    type: OpenJDK
    release: 21
    home: $BUILDS/jdk-lxr/jdk-21.0.9
    commits:
      mmtk-core: 6790b6d78fd1ba019428bc4d40088b18467649cb # lxr
      mmtk-openjdk: 16bd5f9299e98b42309d8e96d8df273099c58518 # lxr-x/jdk21
      openjdk: f3705fcdb1674dda39fa38319080acc89a670229
    features: mmtk/no_meta_counting,mmtk/lxr_stw
    pgo: true
  jdk-lxr-opt: # 0.32.0
    <<: *lxr
    home: $BUILDS/jdk-lxr-2/jdk-21.0.9
    commits:
      mmtk-core: fd148e535b5302e2bec2a8e449d82d64b748af12 # lxr-x/barrier-opt
      mmtk-openjdk: 2696486d7cc76c32bed2c4fb2bc0a35cc1f12693 # lxr-x/jdk21-barrier-opt
      openjdk: f3705fcdb1674dda39fa38319080acc89a670229

configs:
  # G1
  - jdk-lxr|g1|common3|hs|no_class_unload|metaspace1g|dacapochopin_jdk21
  # - jdk-lxr|ix|common3|tph|disable_thp|no_class_unload|metaspace1g|dacapochopin_jdk21
  - jdk-lxr|lxr|common3|tph|disable_thp|no_class_unload|metaspace1g|dacapochopin_jdk21
  - jdk-lxr-opt|lxr|common3|tph|disable_thp|no_class_unload|metaspace1g|dacapochopin_jdk21
  # - jdk-lxr-opt|lxr|common3|tph|disable_thp|no_class_unload|metaspace1g|dacapochopin_jdk21
  # - jdk-lxr-full-only|lxr|common3|tph|disable_thp|no_class_unload|metaspace1g|dacapochopin_jdk21
  # - jdk-lxr-full-only-no-arraycopy|lxr|common3|tph|disable_thp|no_class_unload|metaspace1g|dacapochopin_jdk21
  # - jdk-lxr-no-arraycopy|lxr|common3|tph|disable_thp|no_class_unload|metaspace1g|dacapochopin_jdk21
  # - jdk-lxr-no-arraycopy-slow|lxr|common3|tph|disable_thp|no_class_unload|metaspace1g|dacapochopin_jdk21
