hfac: 2x

includes:
  - $CONFIGS/common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 20
  suites.dacapochopin.minheap: Immix
  benchmarks.dacapochopin:
    - lusearch
    - h2
    - cassandra
    - tomcat
    - spring
    - tradebeans
    - tradesoap
    - kafka

    - avrora
    # - batik
    - biojava
    # - eclipse
    - fop
    - graphchi
    - h2o
    - jme
    - jython
    - luindex
    - pmd
    - sunflow
    - xalan
    - zxing

runtimes:
  jdk-lxr: &lxr
    type: OpenJDK
    release: 11
    home: $BUILDS/jdk-lxr/jdk-11.0.19
    commits:
      mmtk-core: 1ca26a1e46098256c0a575f26c53989639f6b233
      mmtk-openjdk: 2f7da8dc817c1364f6d072ec67eb900536b870a5
      openjdk: bc9669aaedc07924d08b939adedcad33f3e76065
    features: mmtk/no_meta_counting,mmtk/ix_dump_holes
  jdk-lxr-refill:
    <<: *lxr
    home: $BUILDS/jdk-lxr-2/jdk-11.0.19
    commits:
      mmtk-core: 6cb8b8cb8d3f201b2d69fc042eb14284ad2ea9f5
      mmtk-openjdk: 2f7da8dc817c1364f6d072ec67eb900536b870a5
      openjdk: bc9669aaedc07924d08b939adedcad33f3e76065
    features: mmtk/no_meta_counting,mmtk/ix_dump_holes,mmtk/init_bump_pointer_on_medium_alloc

configs:
  # - jdk-lxr|ix|common3|tph
  - jdk-lxr|lxr|common3|tph
  - jdk-lxr-refill|lxr|common3|tph
