hfac: 2x

includes:
  - $CONFIGS/common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 20
  suites.dacapochopin.minheap: Immix
  benchmarks.dacapochopin:
    - lusearch
    - h2
    - cassandra
    - tomcat
    - spring
    - tradebeans
    - tradesoap
    - kafka

    - avrora
    # - batik
    - biojava
    # - eclipse
    - fop
    - graphchi
    - h2o
    - jme
    - jython
    - luindex
    - pmd
    - sunflow
    - xalan
    - zxing

runtimes:
  jdk-lxr: &lxr
    type: OpenJDK
    release: 11
    home: $BUILDS/jdk-lxr/jdk-11.0.19
    commits:
      mmtk-core: 17b2f17d16dc94e0aba0ebb5713365ebf1b68057
      mmtk-openjdk: a0c83638f8da90ed51791a789d6253e016866b9d
      openjdk: bc9669aaedc07924d08b939adedcad33f3e76065
    features: mmtk/no_meta_counting,mmtk/ix_dump_holes

configs:
  - jdk-lxr|ix|common3|tph
  - jdk-lxr|lxr|common3|tph
