hfac: 2x

includes:
  - $CONFIGS/common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 20
  suites.dacapochopin.minheap: G1-n5

runtimes:
  jdk-lxr: &lxr
    type: OpenJDK
    release: 11
    home: $BUILDS/jdk-lxr/jdk-11.0.19
    commits:
      mmtk-core: ec71b2a6ee3884fa822a99ada3aa34f53ef74119
      mmtk-openjdk: 46f70a5da616b4980ef5f7bb85ede21fe316dc60
      openjdk: bc9669aaed
    features: mmtk/no_meta_counting
  jdk-lxr-no-merge:
    <<: *lxr
    home: $BUILDS/jdk-lxr-no-merge/jdk-11.0.19
    features: mmtk/no_meta_counting,mmtk/lxr_no_merge_buckets

configs:
  - jdk-lxr|lxr|common3|tph
  - jdk-lxr-no-merge|lxr|common3|tph
