hfac: 2x

includes:
  - $CONFIGS/common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 20
  suites.dacapochopin.minheap: G1-n5

runtimes:
  jdk-lxr: &lxr
    type: OpenJDK
    release: 11
    home: $BUILDS/jdk-lxr/jdk-11.0.19
    commits:
      mmtk-core: e8ba33683b97fe9a79ec4cab25bab4bd0055679a
      mmtk-openjdk: 00ee1edb55d40c3fba867b261a5c16946a4d5ecd
      openjdk: bc9669aaed
    features: mmtk/no_meta_counting
  jdk-lxr-prefetch:
    <<: *lxr
    home: $BUILDS/jdk-lxr-prefetch/jdk-11.0.19
    features: mmtk/no_meta_counting,mmtk/lxr_prefetch

configs:
  - jdk-lxr|lxr|common3|tph
  - jdk-lxr-prefetch|lxr|common3|tph
