gcbench.jar: GCBench.class Node.class
	/usr/lib/jvm/java-8-openjdk-amd64/bin/jar cfe gcbench.jar GCBench GCBench.class Node.class

GCBench.class: GCBench.java
	/usr/lib/jvm/java-8-openjdk-amd64/bin/javac GCBench.java

