# running runbms ./evaluation/results/log ./evaluation/configs/ix-xput/config.yml 8 1 7 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "../minheap.yml"
  - "../lxr-modifiers.yml"

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-fix-{git}/jdk"
  jdk-lxr-fix:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-fix-{git}/jdk"
overrides:
  suites.dacapochopin-f480064.timing_iteration: 5
  benchmarks.dacapochopin-f480064:
    - fop
    - lusearch
    - cassandra
    - h2o
    - avrora
    - batik
    - biojava
    - eclipse
    - graphchi
    - h2
    - jython
    - luindex
    - pmd
    - sunflow
    - tomcat
    - xalan
    - zxing
    - jme

configs:
  # - jdk|ix|common|tph|mmtk_perf|oevac|lfb-8 # 32M
  # - jdk|ix|common|tph|mmtk_perf|nr-1 # 32M
  # - jdk-4bits|ix|common|tph|mmtk_perf|oevac # 32M
  # - jdk-8bits|ix|common|tph|mmtk_perf|oevac # 32M
  # # - jdk|ix|common|tph|mmtk_perf # 32M
  # - jdk-master|ss|common|tph|mmtk_perf
  # - jdk-master-nolos|ss|common|tph|mmtk_perf
  # - jdk-master-nocalclos|ss|common|tph|mmtk_perf
  # - jdk-master-noweak|ss|common|tph|mmtk_perf|noweak
  # - jdk-fixleak|ss|common|tph|mmtk_perf
  # - jdk-lxr-fixleak|ix|common|tph|mmtk_perf|oevac|defrag_ratio-20
  # - jdk-lxr-old-fixleak|ix|common|tph|mmtk_perf|nr-1

  - jdk-lxr|ix|common|tph|oevac|incs-20000|trace-30
  - jdk-lxr-fixleak|ix|common|tph|oevac|incs-20000|trace-30
  # - jdk-master|ix|common|tph|mmtk_perf
  # - jdk-master-noweak|g1|common|hs_perf|noweak|noclassunload
  # - jdk|ix|common|tph|mmtk_perf|oevac # 32M
