# running runbms ./evaluation/results/log ./evaluation/configs/ix-xput/config.yml 8 1 7 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./_config.yml"

overrides:
  suites.dacapochopin-f480064.timing_iteration: 10
  configs:
    - jdk-master|mc|common|tph|mmtk_perf