# running runbms ./evaluation/results/log ./evaluation/configs/ix-xput/config.yml 8 1 7 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "./_config.yml"

overrides:
  suites.dacapochopin-29a657f.timing_iteration: 5
  configs:
    - jdk-fixleak|ix|common|tph|mmtk_perf