# running runbms ./evaluation/results/log ./evaluation/configs/ix-xput/config.yml 8 1 7 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "../minheap.yml"

runtimes:
  jdk:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-{git}/jdk"
  jdk-4bits:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-{git}-4bits/jdk"
  jdk-8bits:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-{git}-8bits/jdk"
  jdk-master:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-master/jdk"
  jdk-master-nolos:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-master-nolos/jdk"
  jdk-master-nocalclos:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-master-nocalclos/jdk"
  jdk-master-noweak:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-master-noweak-2/jdk"
  jdk-master-ld:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-master-ld/jdk"
  jdk-fixleak:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-fixleak/jdk"
overrides:
  suites.dacapochopin-29a657f.timing_iteration: 5
  benchmarks.dacapochopin-29a657f:
    - fop
    - lusearch
    - cassandra
    - h2o
    - avrora
    - batik
    - biojava
    - eclipse
    - graphchi
    - h2
    - jython
    - luindex
    - pmd
    - sunflow
    - tomcat
    - xalan
    - zxing

modifiers:
  nobarrier:
    type: EnvVar
    var: "BARRIER"
    val: "NoBarrier"
  nb:
    type: EnvVar
    var: "NURSERY_BLOCKS"
    val: "{0}"
  noreuse:
    type: EnvVar
    var: "DISABLE_MUTATOR_LINE_REUSING"
    val: "1"
  nr:
    type: EnvVar
    var: "NURSERY_RATIO"
    val: "{0}"
  lfb:
    type: EnvVar
    var: "LOCK_FREE_BLOCKS"
    val: "{0}"
  oevac_threshold:
    type: EnvVar
    var: "OPPORTUNISTIC_EVAC_THRESHOLD"
    val: "{0}"
  oevac_enable:
    type: EnvVar
    var: "OPPORTUNISTIC_EVAC"
    val: "1"
  oevac:
    type: ModifierSet
    val: "oevac_enable|oevac_threshold-50"
  lfb:
    type: EnvVar
    var: "LOCK_FREE_BLOCKS"
    val: "{}"
  noweak:
    type: JVMArg
    val: "-XX:-RegisterReferences"
  noclassunload:
    type: JVMArg
    val: "-XX:-ClassUnloading -XX:-ClassUnloadingWithConcurrentMark"


configs:
  # - jdk|ix|common|tph|mmtk_perf|oevac|lfb-8 # 32M
  # - jdk|ix|common|tph|mmtk_perf|nr-1 # 32M
  # - jdk-4bits|ix|common|tph|mmtk_perf|oevac # 32M
  # - jdk-8bits|ix|common|tph|mmtk_perf|oevac # 32M
  # # - jdk|ix|common|tph|mmtk_perf # 32M
  # - jdk-master|ss|common|tph|mmtk_perf
  # - jdk-master-nolos|ss|common|tph|mmtk_perf
  # - jdk-master-nocalclos|ss|common|tph|mmtk_perf
  # - jdk-master-noweak|ss|common|tph|mmtk_perf|noweak
  - jdk-fixleak|ss|common|tph|mmtk_perf
  # - jdk-master|ix|common|tph|mmtk_perf
  # - jdk-master-noweak|g1|common|hs_perf|noweak|noclassunload
  # - jdk|ix|common|tph|mmtk_perf|oevac # 32M
