# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "../common.yml"
  - "../lxr-modifiers.yml"

overrides:
  invocations: 3
  suites.dacapochopin-29a657f.minheap: g1
  benchmarks.dacapochopin-29a657f:
    - fop
    - lusearch
    # - tradebeans
    # - tradesoap
    - cassandra
    - h2o
    - avrora
    - batik
    - biojava
    - eclipse
    - graphchi
    - h2
    # - jme
    - jython
    # - kafka
    - luindex
    - pmd
    - sunflow
    - tomcat
    - xalan
    - zxing

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-{git}/jdk"

plugins:
  dacapo-latency:
    type: CopyFile
    patterns:
      - "scratch/pauses.csv"

configs:
  - jdk-lxr|g1|common|hs_pauses
  # - jdk-lxr|g1_default|common|hs_pauses
  - jdk-lxr|ix|common|tph|nr-1
  - jdk-lxr|shenandoah|common|hs_pauses
  - jdk-lxr|shenandoah|common|hs_pauses|hs_cgc-21
  # - jdk-lxr|z|common|hs_pauses
