# running runbms ./evaluation/results/log ./evaluation/configs/lxr-xput/config.yml 8 3 --skip-oom 1 --skip-timeout 1 > _log

includes:
  - "../common.yml"
  - "../lxr-modifiers.yml"

overrides:
  heap_range: 6
  invocations: 3
  suites.dacapochopin-29a657f.minheap: adoptopenjdk-15-G1
  benchmarks.dacapochopin-29a657f:
    - lusearch
    # - cassandra
    # - tomcat
    # - h2

runtimes:
  jdk-lxr:
    type: OpenJDK
    release: 11
    home: "/home/wenyuz/MMTk-Dev/evaluation/configs/{config}/jdk-lxr-{git}/jdk"

plugins:
  dacapo-latency:
    type: CopyFile
    patterns:
      - "_pauses.csv"

configs:
  - jdk-lxr|ix|common|tph|nr-1
