hfac: 2x

includes:
  - $CONFIGS/common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 20
  suites.dacapochopin.minheap: G1-n5

runtimes:
  jdk-lxr-queue: &lxr # Queue
    type: OpenJDK
    release: 11
    home: $BUILDS/jdk-lxr-queue/jdk-11.0.19
    commits:
      mmtk-core: e37d41151eff58cf402a7fe961e3f4ad791b996f
      mmtk-openjdk: 9b39764a9ae02f31f0b11570f4d00ffef3f433be
      openjdk: bc9669aaed
    features: mmtk/no_meta_counting,mmtk/lxr_no_prefetch
  jdk-lxr-queue-half: # Queue
    <<: *lxr
    home: $BUILDS/jdk-lxr-queue-half/jdk-11.0.19
    features: mmtk/no_meta_counting,mmtk/lxr_no_prefetch,mmtk/flush_half

configs:
  - jdk-lxr-queue|lxr|common3|tph_perf
  - jdk-lxr-queue-half|lxr|common3|tph_perf
