hfac: 2x

includes:
  - $CONFIGS/common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 10
  suites.dacapochopin.minheap: G1-n5

runtimes:
  jdk-mmtk-queue: &lxr
    type: OpenJDK
    release: 11
    home: $BUILDS/jdk-lxr/jdk-11.0.19
    commits:
      mmtk-core: ffa112abfeacfedef8e6da42a25f862aec4de05c
      mmtk-openjdk: a0c83638f8da90ed51791a789d6253e016866b9d
      openjdk: bc9669aaed
    features: mmtk/no_meta_counting,mmtk/no_stack,mmtk/satb_timer
  # jdk-mmtk-stack:
  #   <<: *lxr
  #   home: $BUILDS/jdk-lxr-2/jdk-11.0.19
  #   features: mmtk/no_meta_counting,mmtk/push,mmtk/lxr_no_prefetch,mmtk/satb_timer
  # jdk-mmtk-stack-steal:
  #   <<: *lxr
  #   home: $BUILDS/jdk-lxr-3/jdk-11.0.19
  #   features: mmtk/no_meta_counting,mmtk/push,mmtk/steal,mmtk/lxr_no_prefetch,mmtk/satb_timer
  jdk-mmtk-stack-steal-bulk-no-prefetch:
    <<: *lxr
    home: $BUILDS/jdk-lxr-3/jdk-11.0.19
    features: mmtk/no_meta_counting,mmtk/push,mmtk/steal_bulk,mmtk/satb_timer,mmtk/lxr_no_prefetch
  jdk-mmtk-stack-steal-bulk:
    <<: *lxr
    home: $BUILDS/jdk-lxr-4/jdk-11.0.19
    features: mmtk/no_meta_counting,mmtk/push,mmtk/steal_bulk,mmtk/satb_timer
  jdk-mmtk-queue-no-prefetch:
    <<: *lxr
    home: $BUILDS/jdk-lxr-5/jdk-11.0.19
    features: mmtk/no_meta_counting,mmtk/no_stack,mmtk/satb_timer,mmtk/lxr_no_prefetch

configs:
  - jdk-mmtk-queue|lxr|common3|tph_perf
  - jdk-mmtk-queue-no-prefetch|lxr|common3|tph_perf
  # - jdk-mmtk-stack|lxr|common3|tph_perf
  - jdk-mmtk-stack-steal-bulk-no-prefetch|lxr|common3|tph_perf
  - jdk-mmtk-stack-steal-bulk|lxr|common3|tph_perf
