hfac: 2x

includes:
  - $CONFIGS/common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 10
  suites.dacapochopin.minheap: Immix
  benchmarks.dacapochopin:
    - lusearch
    - h2
    - cassandra
    - tomcat
    - spring
    - tradebeans
    - tradesoap
    - kafka

    - avrora
    # - batik
    - biojava
    # - eclipse
    - fop
    - graphchi
    - h2o
    - jme
    - jython
    - luindex
    - pmd
    - sunflow
    - xalan
    - zxing

runtimes:
  jdk-mmtk-queue: &lxr
    type: OpenJDK
    release: 11
    home: $BUILDS/jdk-lxr/jdk-11.0.19
    commits:
      mmtk-core: 4b604208f71f393e57fb38a298180d5a272f0439
      mmtk-openjdk: 4aec297305e5e1047d2f8eee1f8a9097d1084d1d
      openjdk: bc9669aaed
    features: mmtk/no_meta_counting,mmtk/no_stack,mmtk/push
  jdk-mmtk-stack:
    <<: *lxr
    home: $BUILDS/jdk-lxr-2/jdk-11.0.19
    features: mmtk/no_meta_counting,mmtk/push
  jdk-mmtk-stack-steal-lifo:
    <<: *lxr
    home: $BUILDS/jdk-lxr-3/jdk-11.0.19
    features: mmtk/no_meta_counting,mmtk/push,mmtk/steal
  jdk-mmtk-stack-steal-lifo-bulk:
    <<: *lxr
    home: $BUILDS/jdk-lxr-4/jdk-11.0.19
    features: mmtk/no_meta_counting,mmtk/push,mmtk/steal_bulk
  jdk-mmtk-stack-steal-fifo:
    <<: *lxr
    home: $BUILDS/jdk-lxr-5/jdk-11.0.19
    features: mmtk/no_meta_counting,mmtk/push,mmtk/steal,mmtk/fifo
  jdk-mmtk-stack-steal-fifo-bulk:
    <<: *lxr
    home: $BUILDS/jdk-lxr-6/jdk-11.0.19
    features: mmtk/no_meta_counting,mmtk/push,mmtk/steal_bulk,mmtk/fifo

configs:
  - jdk-mmtk-queue|ix|common3|tph_perf
  - jdk-mmtk-stack|ix|common3|tph_perf
  - jdk-mmtk-stack-steal-lifo|ix|common3|tph_perf
  - jdk-mmtk-stack-steal-lifo-bulk|ix|common3|tph_perf
  - jdk-mmtk-stack-steal-fifo|ix|common3|tph_perf
  - jdk-mmtk-stack-steal-fifo-bulk|ix|common3|tph_perf
