hfac: 2x

includes:
  - $CONFIGS/common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 10
  suites.dacapochopin.minheap: G1-n5

runtimes:
  jdk-mmtk-queue: &lxr
    type: OpenJDK
    release: 11
    home: $BUILDS/jdk-lxr/jdk-11.0.19
    commits:
      mmtk-core: 47ee34b99bcef5f6f2fc0cc323bdcecd25f50c56
      mmtk-openjdk: c4c4dda4848b4832265157f76c13e52ba5b7d582
      openjdk: bc9669aaed
    features: mmtk/no_meta_counting,mmtk/push,mmtk/no_stack
  jdk-mmtk-stack:
    <<: *lxr
    home: $BUILDS/jdk-lxr-2/jdk-11.0.19
    features: mmtk/no_meta_counting,mmtk/push
  jdk-mmtk-stack-steal:
    <<: *lxr
    home: $BUILDS/jdk-lxr-3/jdk-11.0.19
    features: mmtk/no_meta_counting,mmtk/push,mmtk/steal
  jdk-mmtk-stack-steal-bulk:
    <<: *lxr
    home: $BUILDS/jdk-lxr-4/jdk-11.0.19
    features: mmtk/no_meta_counting,mmtk/push,mmtk/steal_bulk
  jdk-mmtk-stack-steal-bulk-no-push:
    <<: *lxr
    home: $BUILDS/jdk-lxr-5/jdk-11.0.19
    features: mmtk/no_meta_counting,mmtk/steal_bulk

configs:
  - jdk-mmtk-queue|lxr|common3|tph_perf
  - jdk-mmtk-stack|lxr|common3|tph_perf
  - jdk-mmtk-stack-steal|lxr|common3|tph_perf
  - jdk-mmtk-stack-steal-bulk|lxr|common3|tph_perf
  - jdk-mmtk-stack-steal-bulk-no-push|lxr|common3|tph_perf
