hfac: 2x

includes:
  - $CONFIGS/common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 10
  suites.dacapochopin.minheap: G1-n5

runtimes:
  jdk-mmtk-baseline: &base
    type: OpenJDK
    release: 11
    home: $BUILDS/jdk-lxr/jdk-11.0.19
    commits:
      mmtk-core: cc0f8031727d4700152940266d588fdaf2490c63 # wp/dev-baseline
      mmtk-openjdk: a0c83638f8da90ed51791a789d6253e016866b9d # wp/dev-baseline
      openjdk: bc9669aaed
    features: mmtk/no_meta_counting,mmtk/push,mmtk/satb_timer,mmtk/utilization
  jdk-mmtk-item-stealing:
    <<: *base
    home: $BUILDS/jdk-lxr-2/jdk-11.0.19
    commits:
      mmtk-core: fbc42291427b201712abef9a3556cf7402d0ddc2 # wp/dev-stealing
      mmtk-openjdk: a0c83638f8da90ed51791a789d6253e016866b9d # wp/dev-baseline
      openjdk: bc9669aaed
    features: mmtk/no_meta_counting,mmtk/push,mmtk/satb_timer,mmtk/utilization,mmtk/steal_bulk
  jdk-mmtk-dependency:
    <<: *base
    home: $BUILDS/jdk-lxr-3/jdk-11.0.19
    commits:
      mmtk-core: 0e9f3c180caecc241933c5e9967c21fb5f5cad33 # wp/dev-dep
      mmtk-openjdk: 65fa88d8fcd58890bd64c211ff1a21e36a642532 # wp/dev-dep
      openjdk: bc9669aaed
  jdk-mmtk-all:
    <<: *base
    home: $BUILDS/jdk-lxr-4/jdk-11.0.19
    commits:
      mmtk-core: 822083539538192382ce0a3540d2d75dd04604a7 # wp/dev-merge
      mmtk-openjdk: 65fa88d8fcd58890bd64c211ff1a21e36a642532 # wp/dev-dep
      openjdk: bc9669aaed
    features: mmtk/no_meta_counting,mmtk/push,mmtk/satb_timer,mmtk/utilization,mmtk/steal_bulk

configs:
  - jdk-mmtk-baseline|g1|common3|hs_perf
  - jdk-mmtk-baseline|lxr|common3|tph_perf
  - jdk-mmtk-item-stealing|lxr|common3|tph_perf
  - jdk-mmtk-dependency|lxr|common3|tph_perf
  - jdk-mmtk-all|lxr|common3|tph_perf
  - jdk-mmtk-baseline|ix|common3|tph_perf
  - jdk-mmtk-item-stealing|ix|common3|tph_perf
  - jdk-mmtk-dependency|ix|common3|tph_perf
  - jdk-mmtk-all|ix|common3|tph_perf
