hfac: 2x

includes:
  - $CONFIGS/common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 8
  suites.dacapochopin.minheap: Immix
  benchmarks.dacapochopin:
    - lusearch
    - h2
    - cassandra
    - tomcat
    - spring
    - tradebeans
    - tradesoap
    - kafka

    - avrora
    # - batik
    - biojava
    # - eclipse
    - fop
    - graphchi
    - h2o
    - jme
    - jython
    - luindex
    - pmd
    - sunflow
    - xalan
    - zxing

runtimes:
  jdk-lxr: &lxr # Sequential
    type: OpenJDK
    release: 11
    home: $BUILDS/jdk-lxr/jdk-11.0.19
    commits:
      mmtk-core: fe4cff2affe2bc4dc3cf2c5d9b208643fe4c9afd # wp/lxr-ix-reduce-buckets
      mmtk-openjdk: e29fd88109231765442ed68640ab68a407815454
      openjdk: bc9669aaed
    features: mmtk/no_meta_counting,mmtk/ix_always_defrag
  jdk-lxr-2: # Dependency
    <<: *lxr
    home: $BUILDS/jdk-lxr-2/jdk-11.0.19
    commits:
      mmtk-core: 201f88d38cfd6a17ff52b7fca29feaf16fb0efe2 # wp/dep-dev
      mmtk-openjdk: 66fbb66a05605a8136e8a01a1d13a01a679d3b3b
      openjdk: bc9669aaed

configs:
  - jdk-lxr|ix|common3|tph|threads-16
  - jdk-lxr-2|ix|common3|tph|threads-16
  # - jdk-lxr|ix|common3|tph|threads-32
  # - jdk-lxr-2|ix|common3|tph|threads-32
  # - jdk-lxr|ix|common3|tph|threads-64
  # - jdk-lxr-2|ix|common3|tph|threads-64
  - jdk-lxr|ix|common3|tph|threads-128
  - jdk-lxr-2|ix|common3|tph|threads-128
