hfac: 2x

includes:
  - $CONFIGS/common/common-lxr.yml

overrides:
  heap_range: 3
  invocations: 10
  suites.dacapochopin.minheap: G1-n5

runtimes:
  jdk-lxr: &lxr
    type: OpenJDK
    release: 11
    home: $BUILDS/jdk-lxr/jdk-11.0.19
    commits:
      mmtk-core: c5d66c271a0919997cda758ca689066da4387559
      mmtk-openjdk: e29fd88109231765442ed68640ab68a407815454
      openjdk: bc9669aaed
    features: mmtk/no_meta_counting
  jdk-lxr-2:
    <<: *lxr
    home: $BUILDS/jdk-lxr-2/jdk-11.0.19
    commits:
      mmtk-core: afc940a44ff80ec16bbd35976dc76da2a7f3fd9c
      mmtk-openjdk: 66fbb66a05605a8136e8a01a1d13a01a679d3b3b
      openjdk: bc9669aaed

configs:
  - jdk-lxr|ix|common3|tph|threads-16
  - jdk-lxr-2|ix|common3|tph|threads-16
  - jdk-lxr|ix|common3|tph|threads-32
  - jdk-lxr-2|ix|common3|tph|threads-32
  - jdk-lxr|ix|common3|tph|threads-64
  - jdk-lxr-2|ix|common3|tph|threads-64
  - jdk-lxr|ix|common3|tph|threads-128
  - jdk-lxr-2|ix|common3|tph|threads-128
